### ISSUE TITLE
Ledger.Index.TxOutRefNotFound error while using payToWallet_ function

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/plutus#1042]
Gist: 7164fbe87e43e0c9d65cdd326b298192

1. compile any contract (Game in my case)
2. use the default 2 Wallets
3. add 2 identical payToWallet_ actions
- from Wallet 1 to Wallet 2
- ivFrom = 2
- ivTo = 3
- Value = 2
4. evaluate Simulation

Inside the Transactions tab we have this error: "Validation failed for transaction: 9f18b91870186e18c10118bd1863185f184d18f0186f185b184e187718a3184218c918b91896189718ed1883187818b2183d04182718b31318ef182518f7ff
 Ledger.Index.TxOutRefNotFound (Ledger.Tx.TxOutRefOf {txOutRefId: Ledger.TxId.TxIdOf {getTxId: "9f18be18e01822041840186018ca1883187318c818f718fd02185718a9187418d918a718541875183618671866031864189418e7170f1898182e182eff"}, txOutRefIdx: 0})"

![image](https://user-images.githubusercontent.com/29144964/58252535-0c236980-7d6f-11e9-82be-c41f714ac0c4.png)

**Comment by j-mueller** [comment]
Again this has to do with the validation ranges (like #1043). When the first `payToWallet_` action is run by the wallet, the transaction stays in the emulator's pool of pending transactions until slot 2, when it can be validated. But when slot 2 comes around the second `payToWallet_` action is run by the same wallet. When doing coin selection the wallet does not know that some of its own funds were selected for the earlier transaction - those funds are still in the utxo set because the first transaction hasn't been added to the chain yet. So it ends up submitting the exact same transaction again. When the first of the two txns has been validated its inputs disappear from the UTXO set, so validating the second transaction fails with the `TxOutRefNotFound` error.

**Comment by dorin100** [comment]
Hmm... this makes sense from a code perspective but not from an end user's one. 

Maybe this could be a limitation of the simulated blockchain but it would not be seen on the live one? Even so, my feeling is that the above explanation would not come naturally for most of the end users seeing that error.

**Comment by j-mueller** [comment]
It would happen on the live one too if you submitted the same transaction twice.

But #1048 removes the validity range parameter from the `payToWallet_` endpoint, so it won't be possible to run this scenario anymore.

**Comment by dorin100** [comment]
Ok. Waiting for #1048 to be available on dev env. Thank you.

**Comment by michaelpj** [comment]
Well, it could still be the case that your transaction isn't validated immediately. So the wallet should keep track of outputs it's provisionally spent and not consider them available. I think it's a weakness in our modelling of the wallet, perhaps.
