### ISSUE TITLE
Only 5 out of 8 transactions are executed/validated (and none indications displayed) when using payToWallet_

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/plutus#1043]
Gist: c0ea049ae7dd7c1948e245dc72873c8f

There are 6 wallets and 8 actions configured inside the Simulation tab. 

Wallets (initialBalance / expectedBalance)
  w1 - 11 / 228
  w2 - 289 / 3788      
  w3 - 1284 / 1216
  w4 - 1839 / 1821
  w5 - 8538 / 4918
  w6 - 728 / 718 

Actions (actionNo - walletSource - walletDestination - Value(payToWallet) - ivFrom - ivTo)
  1 w1 -> w3 - 1 		2 to 4
  2 w2 -> w5 - 125	        1 to 5
  3 w3 -> w6 - 69		2 to 9
  4 w4 -> w1 - 218	        2 to 5
  5 w5 -> w2 - 2498	        3 to 4
  6 w6 -> w4 - 200	        3 to 7
  7 w2 -> w6 - 121	        4 to 7
  8 w5 -> w2 - 1247  	4 to 9

The final balances (from Transaction page) are different than expected because only 5 out of 8 transactions are executed. The other 3 are not executed (can be seen also inside the Blockchain graph). No errors displayed under logs. 

Executed/Validated Actions
  1 w1 -> w3 - 1 		2 to 4
  2 w2 -> w5 - 125	        1 to 5
  3 w3 -> w6 - 69		2 to 9
  4 w4 -> w1 - 218	        2 to 5
  6 w6 -> w4 - 200	        3 to 7

![image](https://user-images.githubusercontent.com/29144964/58253356-edbe6d80-7d70-11e9-8a61-8fb243f507f6.png)

**Comment by j-mueller** [comment]
@dorin100 The validation ranges of the missing transactions are

**w5** (Slot 3- slot 4) - can only be validated during slot 3 but it's submitted later (during slot 5)
**w7** (Slot 4 - slot 7) - can only be validated between during slot 4, 5 and 6 but is submitted during slot 7
**w8** (Slot 9 - slot 4  - note this is different from what you wrote above) - can never be validated but is submitted during slot 8

So this is the expected behaviour. But I think I'll remove the `SlotRange` parameter from `payToWallet_` and put in an unlimited range by default. That should make it less confusing.

**Comment by dorin100** [comment]
Ok. Removing the SlotRange should fix/align the expectations of this scenario. Otherwise, it would be a little difficult to understand why **w5 (Slot 3- slot 4)** should be validated between slots 3 and 4 but it is submitted only in slot 5.

**Comment by j-mueller** [comment]
The playground runs at most 1 action per slot, so the fifth action can only run in slot 5.

**Comment by j-mueller** [comment]
The playground runs at most 1 action per slot, so the fifth action can only run in slot 5.
