### ISSUE TITLE
value restriction not enforced by metatheory

### ISSUE THREAD

**Issue by jmchapman** [input-output-hk/plutus#1107]
Until now this wasn't enforced. It had the useful side-effect that we don't need to reduce under binders so we only needed to prove progress for closed terms. ~The value restriction requires computing under big lambda so we will need to prove progress for open terms.~

**Comment by jmchapman** [comment]
At the moment I still don't have the value restriction but I do have support for computing under big lambda. It was implemented by proving progress for open terms, so terms could get stuck on a variable and then we showed that there are no neutral terms in the empty context. But, this is not necessary. Big lambda only introduces type variables and reduction cannot get stuck on those.

**Comment by michaelpj** [comment]
I hadn't quite twigged, but this isn't *just* a matter of what programs you accept. If you don't have the value restriction your typed semantics *has* to reduce under big lambdas otherwise erasure won't work.

So if we wanted to bring the spec/implementation in line with the metatheory it wouldn't just be a case of dropping the restriction, we'd also have to change the machines etc. I *think* that would be okay.

**Comment by kwxm** [comment]
This has a bearing on untyped evaluation.  In the interests of reducing code size we may want to erase types before submitting code to the chain and then evaluate it on an untyped evaluator (or we may do Merklisation instead).  

If we don't have the value restriction then we can have a term like `(abs A (type) (error A))` which erases to `(error)`, which will fail immediately.  Thus if we don't have the value restriction we must have computation under `abs` in order to preserve semantics.

**Comment by jmchapman** [comment]
Sketch of changes required to the CK machine:

You need another frame:
```
(abs a K _) -- abstraction body
```

```
s |> (abs a K V) |-> s <| (abs a K V) -- replace 
s |> (abs a K M) |-> s , (abs a K _) |> M -- with
```
add:
```
s , (abs a K _) <| V |-> s <| abs a K V 
```
The below existing rule does not maintain the type annotations. In the metatheory I do maintain them, I don't believe computing under lambdas changes things here:
```
s , {_ A} <| abs a K V |-> s |> V
```

**Comment by kwxm** [comment]
> Sketch of changes required to the CK machine:

This looks reasonable.  Are we going to reawaken the value restriction debate though?  I keep thinking it's gone, but it always comes back to life.

**Comment by kwxm** [comment]
I guess this issue also interacts with extensible builtins (#581, #487): whatever we end up doing, we have to make sure that the machinery for builtins respects it.  For example, if we do have the value restriction then people shouldn't be able to implement new builtins which return abstractions whose bodies aren't values.  At present there's no way of enforcing this, so it's something that would need to be specified (and we will have to write a specification of the extensible builtin stuff once it's settled). 

We could also add a `Value` type to the AST, which might not be a bad idea anyway: values play quite an important part in the PLC specification, but in the code they're not distinguished from terms. I haven't thought this through though.

**Comment by michaelpj** [comment]
> For example, if we do have the value restriction then people shouldn't be able to implement new builtins which return abstractions whose bodies aren't values.

Yikes, I hadn't even thought about that. I think this won't be a problem in practice, but it's certainly annoying on the theoretical level.
