### ISSUE TITLE
Find some way to identify a script given only the script hash

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1140]
Given a locked output, I need to know what validator I'm supposed to provide. This requires some  metadata that identifies it somehow.
- The dumbest version of this is where the metadata is the script itself.
- The metadata could be a description of how to create the validator script again.
    - The [metadata](https://solidity.readthedocs.io/en/v0.5.9/metadata.html) that Solidity includes with a contract is an example of this.
   - See https://github.com/input-output-hk/plutus/issues/1138 for discussion on whether this is feasible.

The metadata could either be part of the transaction, or you could get it some other way.
- If the metadata is the script itself, then storing it in the transaction amounts to doing pay-to-script instead of pay-to-script hash.
    - The question of whether we can do pay-to-script needs to be discussed separately.
- Keeping the metadata outside the transaction adds an extra component that clients need to interact with in order to make transactions, which would be a shame.

Other ways you could get the metadata:
- Counterparty emails it to you.
    - Not viable at scale but probably viable for small examples.
- Counterparty hosts it in some public discoverable location.
    - e.g. the way Ethereum folks check their compiled Solidity into Git.
- Stored in IPFS.
    - MPJ thinks IPFS is not ready for serious use yet, but that may be wrong.
- Stored in something like Ethereum's Swarm.
- Stored in some other on-chain datastructure.
    - This adds more size constraints to what we store.

**Comment by michaelpj** [comment]
Email discussion: https://groups.google.com/a/iohk.io/forum/?hl=en-GB#!topic/plutus/6rbLEqRxBFs

**Comment by mchakravarty** [comment]
Here is a first step in an effort to break this problem into simpler pieces. When we compile a contract, we should have the option of dumping the Plutus Tx for every on-chain script. In other words, for every call to `Ledger.compileScript` in a slice, we want to dump its argument.

Why does this matter? Because this argument is all we are really interested in. All these Plutus Tx scripts generated when compiling a single contract constitute the source form of only the *on-chain* component of the contract. This is precisely what you need to analyse if you want to make sure that you can trust the on-chain portion of a contract.

This also simplifies #1138 — all we need to control is the compilation of these Plutus Tx scripts. Everything else may happily vary from one compile run to another. 

When somebody deploys a contract to the chain, it might be reasonable to require that they store the Plutus Tx scripts generated during compilation of the contract and that is, hence, the basis of the PLC that is being deployed. If we embed a hash of the Plutus Tx script from which a serialised blob of PLC was generated into the PLC script, we would have a definitive link to the PLC source. (That Plutus Tx hash would obviously be part of the input to the PLC hash and hence to the script address.)

**Comment by mchakravarty** [comment]
(A problem here is the new treatment of free variables via unfoldings. Instead of source Plutus Tx, we could of course dump, unfolded GHC Core, but that is much less useful.)

**Comment by michaelpj** [comment]
(Did you mean to make these comments on https://github.com/input-output-hk/plutus/issues/1138? This issue is about getting from the hash to the PLC, the other one is about getting from the serialized PLC to the source.)

> When we compile a contract, we should have the option of dumping the Plutus Tx for every on-chain script

Nit, but I don't think we should talk about the Plutus Tx". Given that the same Haskell can be used from both on- and off-chain code I don't think we can sensibly talk about a separate "Plutus Tx". So we're dumping a subset of the source Haskell of the program.

> In other words, for every call to Ledger.compileScript in a slice, we want to dump its argument. ...
>
> Why does this matter? Because this argument is all we are really interested in.

This might have been true when we were inlining everything via TH but it's not true now. Consider that the argument to `compileScript` is now frequently a single variable reference to the function that defines the validator.

So we actually need everything that's transitively referenced by the splice. This is both a lot and non-trivial to acquire. Dumping Core doesn't help - there is no such thing as "unfolded" Core, we handle the unfolding as definitions when we see them. It's also, again, very sensitive to GHC.

Okay, so we could dump the generated IR. That *is* self-contained, and we could certainly do it. Maybe it's even enough for https://github.com/input-output-hk/plutus/issues/1138 - the IR might be comprehensible enough that you could work out what it was doing without needing the *Haskell* source, which would achieve the main purpose.

> All we need to control is the compilation of these Plutus Tx scripts. Everything else may happily vary from one compile run to another.

This doesn't seem like a meaningful simplification to me. "These Plutus Tx scripts" means "a series of interdependent bindings across multiple packages created in many compilations orchestrated by a build tool" which is basically the full problem.

**Comment by mchakravarty** [comment]
> (Did you mean to make these comments on #1138? This issue is about getting from the hash to the PLC, the other one is about getting from the serialized PLC to the source.)

This really applies to both.

> > When we compile a contract, we should have the option of dumping the Plutus Tx for every on-chain script
> Nit, but I don't think we should talk about the Plutus Tx. 

On the contrary, I think, the problem of identifying the source of PLC is why we —after all— do have to talk about Plutus Tx.

> Given that the same Haskell can be used from both on- and off-chain code I don't think we can sensibly talk about a separate "Plutus Tx". So we're dumping a subset of the source Haskell of the program.

Call it what you want. When I say "Plutus Tx", I mean the subset of Haskell we compile to PLC. (If only, because it is easier to say than "the subset of Haskell we compile to PLC".)

I am very deliberately not talking about code that could or could not be used on-chain. I am talking about the code that is used on-chain by a specific use of `Ledger.compilerScript`. For a specific call to this function during a specific compilation run, that is a specific set of definitions. That is what I am interested in. (I am not saying it is easy to compute, but it is well defined.)

> > All we need to control is the compilation of these Plutus Tx scripts. Everything else may happily vary from one compile run to another.
> This doesn't seem like a meaningful simplification to me. "These Plutus Tx scripts" means "a series of interdependent bindings across multiple packages created in many compilations orchestrated by a build tool" which is basically the full problem.

Again, I am not interested in what can or cannot go in there. I am interested in the transitive closure of the argument of a specific invocation of `Ledger.compilerScript`. This is well defined. If it weren't, the compiler could not work.

Yes, this is harder to compute now that we use unfoldings. However, I think, it goes to the core of the problem. It identifies the code that does contribute to the meaning of a specific piece of on-chain code. If we cannot identify that, how can we hope to ever say anything meaningful about the semantics of the on-chain portion of a contract? In other words, this is something we need to figure out anyway. Not just to fingerprint code, but also to talk about correctness etc.

**Comment by michaelpj** [comment]
> I am interested in the transitive closure of the argument of a specific invocation of Ledger.compilerScript. This is well defined. If it weren't, the compiler could not work.

I'm still not sure what you want to *do* with this and what you think that will achieve. If it's just the source fragments it would not be compilable, nor would it determine the output PLC.

If you *do* want "all the things that affected the output of `compileScript` then you are once again back to worrying about language extensions, compiler flags, order-dependence of bindings, desugaring, who knows what.

Or... you want the PIR. I still think that's potentially the most useful thing here. It's the first stage at which we control the entire input, it's comprehensive, it's still relatively readable, and it's pretty close to (at least) the Core it came from. 

> If we cannot identify that, how can we hope to ever say anything meaningful about the semantics of the on-chain portion of a contract? In other words, this is something we need to figure out anyway. Not just to fingerprint code, but also to talk about correctness etc.

I don't think this is realistically going to help us with talking about correctness. I'm not sure how we *are* going to talk about correctness, given that we have a massive blob of unverified GHC code in the middle of our process, but we can still use tools like types (or liquid types) to carry over correctness properties and check them on the output code too.
