### ISSUE TITLE
Ambiguous syntax for builtin application

### ISSUE THREAD

**Issue by kwxm** [input-output-hk/plutus#1143]
In the grammar for Plutus Core we have this for application of built-in functions:
```
   (builtin bn A* M*)
```
where the `A`s are types and the `M`s are terms.  @michaelpj points out that this is ambiguous because we can't tell where the type arguments end and the term arguments start.  It may be arguable whether this is in fact ambiguous: by the time we see this we can probably tell which things are types and which things are terms, so maybe a parser that's been paying attention could work out what's what.  That would complicate things though, so it's probably easier just to add some new syntax.

@michaelpj  suggests `(seq A_1 ... A_n)` for the type variables, but that disturbs me a bit because all of the other `(xyz ...)` things are independent entities that can be nested inside other things, whereas we'd only ever see `(seq ...)` in a built-in application.

I'm leaning towards `{A_1 ... A_n}` because then we can write `(builtin bn {A_1 ... A_n} M_1 ... M_k)` and it's reminiscent of the `{M A}` syntax for type instantiation.  If we want to be really consistent we should write something like `({(builtin bn) A_1 ... _A_n} M_1 ... M_k)`, but that's a bit messy.

This isn't a big deal.  We should choose something, implement it, then forget about it.

**Comment by michaelpj** [comment]
> @michaelpj suggests (seq A_1 ... A_n) for the type variables, but that disturbs me a bit because all of the other (xyz ...) things are independent entities that can be nested inside other things, whereas we'd only ever see (seq ...) in a built-in application.

The other productions are *not* independent things. They can only appear in places in the grammar where they're listed! Similarly, a sequence of things would only occur where it's listed, which would in this case only be in builtin applications. e.g.
```
tys ::= (seq A...)
ts ::= (seq M...)
term ::= ... | (builtin bn tys ts)
```
Note that it's not ambiguous to use `seq` for both type sequences and term sequences because it's disambiguated by where they appear, like using `lam` for both term and type lambdas.

My other reason for wanting this is that PIR has some productions that have sequences of things that *aren't* ambiguous, but for reasons like "it's a list of Xs followed by one Y, so you know the last one is a Y", which is a bit gross, and I'd prefer to have the sequences explicitly delimited.

> I'm leaning towards {A_1 ... A_n} because then we can write (builtin bn {A_1 ... A_n} M_1 ... M_k) and it's reminiscent of the {M A} syntax for type instantiation.

I really don't like this. It looks like the first type is being instantiated with the other types. I would say that is actively inconsistent. If we were like Agda where type instantiation was `x {A}` (instead of `{x A}` as we have it), then I think it would be fine. But we don't do that.

**Comment by kwxm** [comment]
What do we write when the sequence is empty (as it will always be at the moment)?

**Comment by michaelpj** [comment]
`(seq)` I guess?

**Comment by kwxm** [comment]
Hmmm.

**Comment by kwxm** [comment]
Just giving this a prod to remind us to deal with it.  I'm not hugely keen on `(seq ...)` because it's empty for all our current builtins so we'll have stuff like ``[(builtin addInteger) (seq) (con 3) (con 5)]` all over the place. Could we optionally miss it out if it's empty?  Could we have explicit type instantiation when we need it, like `[{(builtin b) T1 T2} v1 v2 v3]`?  Does anyone really care?  This doesn't really matter at the moment because all builtins are monomorphic but I suppose it might become more relevant if we eventually get extensible builtins.

Maybe the simplest thing to do is just to implement something unilaterally to get it out of the way.

**Comment by michaelpj** [comment]
>  I'm not hugely keen on (seq ...) because it's empty for all our current builtins so we'll have stuff like ``[(builtin addInteger) (seq) (con 3) (con 5)]all over the place. Could we optionally miss it out if it's empty?

PLC is not supposed to be user-readable, so I don't care :laughing: 

> Could we have explicit type instantiation when we need it, like [{(builtin b) T1 T2} v1 v2 v3]`?

This looks precisely like having unsaturated builtins to me: what is `(builtin b)`?

If we have unsaturated builtins I think this problem goes away, since we already have syntax for applying a bunch of types and values. If we don't, then the very problem is "how do we represent a saturated application of some types and values?".

Perhaps this is an argument for unsaturated builtins, although it seems like a weak one. At least, it suggests it's hard to resolve this without resolving the saturation question.

**Comment by kwxm** [comment]
> This looks precisely like having unsaturated builtins to me: what is `(builtin b)`?

OK, good point.

Just go ahead and implement something. Then it'll be a _fait accompli_ and I'll shut up.

**Comment by kwxm** [comment]
This is done in #2031.  It now uses `(builtin {bn A_1 ... A_k} M_1 ... M_n)` and optionally `(builtin bn M_1 ... M_n)` if k=0.
