### ISSUE TITLE
Should we support Applicative/Monad?

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1163]
We can actually do this now! With `RebindableSyntax` we could maybe even get `do` notation working.

The question is whether this is a good idea or not. I'm not sure that it is: we probably don't want people to write on-chain scripts with massive towers of monad transformers. On the other hand, using it for a simple state monad or similar might be fine.

**Comment by j-mueller** [comment]
I think we should. The promise of Plutus is to write smart contracts in Haskell, so the more Haskell we can use the better.

Re.

> we probably don't want people to write on-chain scripts with massive towers of monad transformers

I think we should let people write whatever they want to write. The gas fee & transaction cost should act as an incentive to keep the scripts small anyway (Presumably a monad transformer has a bigger impact on PLC script size than on compiled Haskell program size due to the lack of newtypes?)

**Comment by michaelpj** [comment]
No, we have newtypes. The problem is more that we're not really letting the specialiser loose, so you'll get at lot of indirection. But it might be okay.

**Comment by j-mueller** [comment]
> No, we have newtypes

Ah yes, sorry!

**Comment by michaelpj** [comment]
A reason for doing this might be to allow people to write state machine transition functions in a state-monad style.

**Comment by michaelpj** [comment]
I added `Applicative` and a few instances to make writing parsers easier.
