### ISSUE TITLE
Can't login using the testnet url

### ISSUE THREAD

**Issue by pjcspro** [input-output-hk/plutus#1281]
Hey, 

when clicking on the login button through the address https://testnet.iohkdev.io/plutus/tools/playground/ we are redirected to an empty page (screenshot attacked)

Using the prod address works fine ( https://prod.playground.plutus.iohkdev.io )

I also attached the errors from the console and the headers of the network request, which seem to perform a request for the **production** url instead of the **testnet**.

After clicking on Login:
![plutus playground login error](https://user-images.githubusercontent.com/46036035/60919134-e43f8500-a28c-11e9-9551-5128079ce702.png)

Console:
<img width="1212" alt="console errors" src="https://user-images.githubusercontent.com/46036035/60919577-0ab1f000-a28e-11e9-82ff-9b4348c1ead9.png">

OAuth Request:
<img width="768" alt="github oauth request" src="https://user-images.githubusercontent.com/46036035/60919592-130a2b00-a28e-11e9-8eac-e51c9cb2f92b.png">

**Comment by michaelpj** [comment]
Strange, it seems to work for me.

**Comment by shmish111** [comment]
So it looks like you need to login in full screen mode first, after that saving using the testnet URL will work. I'm not sure there's a workaround to this since OAuth requires you to be redirected back to the domain that you have registered the app with, which in our case is https://prod.playground.plutus.iohkdev.io. Perhaps we could not use the iframe and just have a link to the prod address like we do with Marlowe playground. @krisajenkins what do you think, do you know of a workaround?

**Comment by JamesRobertKelley** [comment]
> Perhaps we could not use the iframe and just have a link to the prod address like we do with Marlowe playground

This is a browser-based restriction using information coming from the webserver's Content Security Policy. There is a line in the current policy that says:

`Content-Security-Policy: frame-ancestors 'self';`

If you change the policy to include the GitHub URL it should load: 

`Content-Security-Policy: frame-ancestors 'self' https://github.com/;`
