### ISSUE TITLE
Self-contained local development environment

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1349]
We'd like people to do some local dev work at the Wyoming hackathon. However, we don't want to waste lots of time getting people set up (not to mention that we haven't tested building our stuff with many configurations).

So, it would be good to provide a pre-pacakged development environment that people can just start using. The goal would be that people could just enter it, fire up an editor, and immediately start writing code in a skeleton project.

My suggestion would be a Docker container (easy for us to build with Nix).

In order of importance, this could contain:
- A skeleton project which depends on our packages and is buildable.
    - How do we make sure our stuff is buildable?
        - Can we put a pre-prepared nix store in the image?
        - If we're confident that it works with `stack` we could just use that
    - How do we set up the project nicely?
        - It doesn't seem that easy to depend on our bunch of unreleased pacakges - I think we'll have to add a *load* of `source-repository-package` stanzas, plus the ones for the dependencies that we pin specific versions of. But at least we can do this for the user!
- Some decent editor preinstalled, ideally with some kind of IDE support set up.
    - I suggest VSCode as an editor, it requires comparatively little configuration, and has plugins for things already. Plus, it's in nixpkgs, along with support for including extensions.
    - I suggest HIE for the IDE part. I think it's at a usable point now. It's not in nixpkgs, but there is support for building it in nix, so we should be able to borrow that. Plus, hopefully we can do any painful configuration bits.

**Comment by mchakravarty** [comment]
Sounds like a good plan. The only issue might be that the VSCode Haskell config probably doesn't know how to deal with a Haskell environment running in a Docker container, so we'll have to see how easy or hard that is to fix up.

**Comment by michaelpj** [comment]
I meant we put VSCode *in* the container. TBH, I don't normally do stuff inside Docker containers so I'm not sure how feasible it is to run a graphical application from inside one.

**Comment by mchakravarty** [comment]
If VSCode is in the container, one option is to use a remote X connection, but that will only work on Linux hosts. 

The other option is to use a VNC connection. This may or may not require installing a separate VNC client on the host. On Mac and Windows that might involve getting a (paid) third party VNC client. I don't know how good VNC client support is on Linux.

It'll also require some experimentation as to whether the performance is sufficient, as going via a remote X connection or VNC will effectively kill all graphic acceleration (which may be quite annoying when scrolling and similar).

Finally, the set up must be such that it properly maps a subtree of the host file system into the container where it is edited (otherwise, all changes get lost when the container terminates). This is not really hard with the right `docker run` options, but it may start to get annoying once you want to edit more than one project at once.

**Comment by michaelpj** [comment]
> I don't know how good VNC client support is on Linux.

Pretty good! I've used them before and there are decent free options.

Possibly we should try and make it work with a VSCode installation on the host, but I don't know how feasible that is.

> This is not really hard with the right docker run options, but it may start to get annoying once you want to edit more than one project at once.

Yeah, although for now I think it's fine if this only works for one project.

**Comment by shmish111** [comment]
I think a VM image is probably better, no?

**Comment by j-mueller** [comment]
> Possibly we should try and make it work with a VSCode installation on the host

According to [this](https://github.com/alanz/vscode-hie-server/issues/78#issuecomment-387339302), std in/out is all that's needed for the HIE VSCode plugin. If this works I'd much prefer it over running VSCode inside docker.

**Comment by shmish111** [comment]
OK, so the plan at the moment is to build a VM image that contains VS Code hooked up to HIE and an example plutus stack project. Docker is not really designed for this type of thing and I think a VM will make everyone's lives much easier.

Building an image tends to be a bit tricky but I am working on creating a NixOS configuration.nix file that contains everything required, there is then a tool https://github.com/nix-community/nixos-generators/ that can be used by someone with a linux computer (not a VM) to build an image for VirtualBox or some other VM hypervisor. Alternatively the configuration.nix file can be used in a running NixOS VM and the machine snapshot distributed. While this is slightly more manual it might mean we can set some minor things up that can't be done in configuration.nix.

Once I have a working configuration.nix I will investigate again the best way to build an image.

**Comment by shmish111** [comment]
Question: we can set up a nice NixOS VM to have vscode and hie installed and working but adding an example project is a bit trickier since it is stateful. I suggest we just have as part of the instructions that you need to clone plutus and copy the example project that I am creating (or alternatively put the example project in a separate repo). The project will be tested with the VM image so it should work just fine, what do you think?

**Comment by shmish111** [comment]
This would also mean that anyone who wants to be a rebel and not use the VM will have an easier time, they should only need nix installed

**Comment by michaelpj** [comment]
Can't we stick a cheeky activation script in there that clones the git repo into the user's home dir or something? I guess if we want them to mount the project into the VM then that's the wrong way around.

Cloning the demo project would be reasonable. Maybe we should just put it in this repository? That would also simplify the setup process: you can use our `stack.yaml`/`cabal.project` and you don't have to deal with `extra-deps`. The cost is that it's not a very "proper" way of doing it, but maybe that's okay?

**Comment by shmish111** [comment]
I thought of the startup script but it's pretty nasty and I don't think it's a big deal to ask people to
```bash
https://github.com/input-output-hk/plutus.git
cd example
nix-shell
cabal new-build
```
Although now that I've written that down I realise that `cabal new-build` will take quite a long time. The activation script would at least get rid of that issue.

Remember we can't use stack at the moment due to those symlink issues but nix-shell and cabal seems fine to me.

**Comment by michaelpj** [comment]
This is in the guest OS, right? It would be nice if we didn't require people to have `nix` installed on their host machine.

`cabal new-build` will take a while, but hopefully not *too* long. It would be cute if we could do it in advance but I wouldn't worry about it too much.

**Comment by shmish111** [comment]
Yeah I mean we will provide a VM with nix, vscode and hie and then the user must clone and build the example project however if they want to they could clone and build on their host machine (or after the course they can)

**Comment by michaelpj** [comment]
Yeah that seems fine.

**Comment by shmish111** [comment]
PR at https://github.com/input-output-hk/plutus/pull/1373

**Comment by j-mueller** [comment]
VSCode has some extensions for running the editor backend (file system as well as compiler, git, etc.) in a process on another machine or in a docker container (https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack)

I got it to work with WSL & the Plutus project yesterday, but the result wasn't great because the type checking plugin kept opening new terminals and in each one it had to run `nix shell` which takes about 20s just to set up the environment.

**Comment by shmish111** [comment]
@michaelpj can this issue be closed now? @j-mueller do you mean in order to run everything  difficult in docker? This might be a nice improvement. Why do they need to nix-shell? If we had a container built with nix then it shouldn't need nix-shell?

**Comment by j-mueller** [comment]
> If we had a container built with nix then it shouldn't need nix-shell?

I initially tried to get it to work with my own setup, which involves nix-shell, but if it runs in a container then you are right, we shouldn't need nix-shell.

**Comment by michaelpj** [comment]
Sure, we can continue this discussion elsewhere.

I thought one of the remaining issues with the VM image we're providing is that people may not be able to easily use their host VSCode with it, and they may have a worse experience using VSCode inside the VM. So it could be good to get the remote support working.
