### ISSUE TITLE
Adding provenance for inputs and outputs.

### ISSUE THREAD

**Issue by raduom** [input-output-hk/plutus#1398]
When balancing transactions, it would be useful to know the reasons why some inputs and outputs are present on the transaction.

If the user asks explicitly the wallet to split an input (for later use), we should not touch any of the specified operations, and use other inputs to add fees and perform balancing. If there are no other inputs available (to pay the fees, for example), we should throw an error describing the issue.

But if the input is added by a *previous* bookkeeping operation, we could remove it and re-balance the transaction, which would allow us to use fewer inputs, for balancing or fees.

The new contracts API will only balance transactions once, so we do know that there is no bookkeeping inputs or outputs in the transaction. As long as the user only specifies the inputs and outputs that make business sense, everything works out.

The old contracts are the reason we've had this conversation. The problem is with balancing and fees. Whenever you add fees to an already balanced contract, you need to re-balance it to allocate inputs. Common sense would dictate that adding fees should be a generic operation automatically performed for all transactions, but due to the need to re-balance, we've run into some limitations.

Example:

1) I want to make a payment of 5 Ada from A to B, where A has 100 Ada funds. We will have an input split into 5 and 95. In this case, it would be ok to take transaction fees from the remaining 95.
2) I want to make a payment of 5 Ada from A to B, and the rest should go back to my wallet. In this case, we should not use the remaining 95 for transaction fees, since the user was specific about their destination, and we should throw an error if no more inputs are available.

However, the transactions in (1) and (2) look the same after balancing, so we have to take the conservative approach assuming (2), which is both annoying and unexpected for the users. Note that if we use the new contract API, we can make this distinction by checking if there is a 95 Ada output specified in the unbalanced transaction.

Michael suggested we could also use this information in the scripts to remove bookkeeping inputs and outputs simplifying life for the contract developers.

**Comment by michaelpj** [comment]
An idea we had was to have one of our transaction types (probably `UnbalancedTx`) have "fungible" and "non-fungible" inputs/outputs, e.g.
`inputs :: [ TxInput ], inputValue :: Value`

The idea is everything in `inputs` has been specifically chosen by the user, and we shouldn't touch it. But `inputValue` is just a request that this value be covered *somehow* and it's up to the wallet how to do this.

We could also have a list of fungible inputs, which are explicitly specified inputs but where we don't care if they're swapped out for other inputs of equivalent value.

-----

The thing I want to simplify life for the contract developer is to actually distinguish fee inputs/change outputs *at the ledger layer*. So they would be explicitly marked somehow, and you'd have the following:
- The fees must be entirely covered by the fee inputs and the change must be entirely taken by the change output.
- The representation of the transaction that we give to scripts does not include fee inputs/change outputs.

The conceptual idea is that our transactions are really two transactions glued together:
- A "fee transaction" that commits funds for the slot leader and returns change to the submitter.
- A "real transaction" that is processed if the fee transaction passes.

Scripts should really only care about the "real" transaction, the rest is bookkeeping.

But this is mostly just My Opinion at the moment.

**Comment by j-mueller** [comment]
@michaelpj 

>  inputs :: [ TxInput ], inputValue :: Value

Isn't a fungible input value the same as a non-fungible output value? Both result in the balancing operation having to add the appropriate inputs.

------

I personally think we should describe unfinished (unbalanced) transactions as sets of constraints. In your example @raduom we would have "spend 100 Ada from A, pay 5 Ada to B" in both cases, and in the 2nd case we would have an additional constraint "pay 95 Ada to (wallet)". We would also have constraints to talk about script outputs, etc.

Then in the wallet we add the validity constraints (txn must be balanced, fee must be above minimum)  and search for a solution. Then

1. Balancing and coin selection are both part of the same operation (solving the constraints)
2. There is a straightforward merge operation for constraints
3. If there is no solution we can identify the constraints that caused the conflict
4. We can say that the solution can result in more than one transaction on the ledger, which gives us a lot of flexibility. For example, the wallet could batch multiple "user transactions" (sets of constraints) into a single ledger transaction to save fees, or it could spread a user transaction across multiple ledger transactions if the constraints are not solvable otherwise (eg. two conflicting constraints on the validity range). This is similar to distinction between fee transactions and real transactions that @michaelpj wrote about.

Ultimately the contracts are interested in outputs, and in changing the outputs from one configuration to another configuration. Transactions are just the tool to make that happen. We already have coin selection and balancing, both of which are steps towards a more declarative way of producing transactions. So the constraint system seems to be the logical next step.

(I realise this is a lot of work and I'm not suggesting we implement it right now. It's also independent of the actual ledger, so maybe we can add it in v2 :) )

**Comment by michaelpj** [comment]
I like this a lot.

My one concern is that scripts have the ability to see the "real transactions" that the wallet produces, so in some cases users may need to have full control over those.

**Comment by j-mueller** [comment]
> My one concern is that scripts have the ability to see the "real transactions" that the wallet produces, so in some cases users may need to have full control over those.

Yeah I agree, and I'm not sure what to do about that. Possibly we need to keep the current system as a fallback for those cases.

**Comment by michaelpj** [comment]
Perhaps this suggests that what we actually want for ledger support is a way to mark inputs/outputs as "invisible to contracts", and then they're not included in what the contract sees. Then we can say "anything constructed by constraint solving is invisible, only stuff added explicitly is visible". We should probably also make the fee field invisible.

Then I think we just need one more piece, which is that if we have a script input then all visible inputs and outputs must remain in the same transaction. At that point we can say "the scripts will always see just the visible inputs and outputs".

**Comment by raduom** [comment]
I definitely like the idea of presenting to the user as little information as possible, removing bookkeeping transactions or balancing algorithms from view.

I am proposing to (possibly) have two modules (something like `Tx.Basic` and `Tx.Advanced`) and clearly explain the guarantees we provide for Basic and the ones we offer for Advanced (none?). Both of these should work with the same data type but exposing very different APIs (new contract API vs old contract API).

I am not sure about eliminating the fee. We need some way to allow the user to specify a fee higher than the minimum fee to incentivise the miners to process the transaction faster. Maybe turn the fee into a delta that we add to the minimum transaction fee.

**Comment by michaelpj** [comment]
> I am proposing to (possibly) have two modules (something like Tx.Basic and Tx.Advanced)

This maps on to the current `Tx` and `UnbalancedTx`, right? I'm not wild about the basic/advanced naming. I think leaving `Tx` as `Tx` (it does represent a transaction faithfully, after all), and maybe something like `TxSpec` for the other thing (since it's a specification for how to build a transaction, but not a transaction itself)?

> I am not sure about eliminating the fee. We need some way to allow the user to specify a fee higher than the minimum fee to incentivise the miners to process the transaction faster. Maybe turn the fee into a delta that we add to the minimum transaction fee.

Do we? I'm not sure. We can add it later - that's one advantage of having a separate data type that doesn't have to faithfully represent the transaction. We could call the field `tip` ;)

**Comment by raduom** [comment]
@michaelpj can we close this issue?

**Comment by raduom** [comment]
Everything discussed here has been merged a while back, no need to keep open.
