### ISSUE TITLE
Fix the `development` docker image to work with VSCode

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#1427]
There's a docker image with all the Plutus libraries that should be usable as a VSCode remote target (https://code.visualstudio.com/docs/remote/containers)

I made a start on this in the j-mueller/docker-2 branch . To test it,

1. clone https://github.com/j-mueller/plutus-template
2. Open it in VS Code with the Container Remote extension installed
3. There should be a prompt about opening this folder in the remote container
4. Click "Yes" and it will download the container and start to install the VSCode related stuff. It will eventually fail with an error `OCI runtime exec failed: exec failed: container_linux.go:296: starting container process caused "no such file or directory": unknown`. The terminal window shows the last instruction it was trying to execute:

```
docker exec -w /root/.vscode-server/bin/3db7e09f3b61f915d03bbfa58e258d6eee843f35 -e SHELL=/nix/store/vlb7kcc1k035vpyrgsj9kk7380yh68wd-bash-4.4-p23/bin/bash -e VSCODE_AGENT_FOLDER=/root/.vscode-server 44148ad69fbd1f6a2e40d75d7a01af4ce5fe6e1fd31afaf44850373282107e8c /root/.vscode-server/bin/3db7e09f3b61f915d03bbfa58e258d6eee843f35/server.sh
```

looking at the `server.sh` script doesn't reveal anything obvious so I need to investigate this further. I think `OCI runtime exec failed` is an error in the docker runtime itself, not in the container.

**Comment by michaelpj** [comment]
[Relevant](https://discourse.nixos.org/t/vscode-remote-development-on-nixos/3119).

In particular there's a horrible workaround for VSCode installing its own node [linked](https://github.com/microsoft/vscode-remote-release/issues/648#issuecomment-503148523). I don't know if that's the issue listed here, but it might well be. If you can ssh into the docker container and mutate things you can probably try out the sequence of steps suggested, as well as adding nodejs to the image.

**Comment by FinleyMcIlwaine** [comment]
I've been investigating this a bit and the issue is definitely a result of the way the node binary used for VSCode's remote server is linked.

What's interesting is that I only run into these linking issues when the devcontainer configuration file uses `dockerComposeFile` or `dockerFile` attributes to build the container. When I attach to the already running container, or use the `image` attribute, the remote server starts just fine, and I can build projects using the libraries just fine. This, and the discussions linked above, leads me to believe this is really just a bug with the VSCode remote server.
