### ISSUE TITLE
playground: TypecheckError  in vesting example

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#1448]
Gist: `e506e0c03cc7b5d94a7a1371d5bfbc7b`
Playground version: 9df04daa5b3e0e174e89eb1d25fcfdb269e61af4

To reproduce:

1. Load the gist
2. Run the simulation

What happens:

The redeeming transaction fails with
```
Validation failed: 9f184f18dd18c4185d18ae187e18a31866186918cb18d6185f183c1888181c186a183318c50118cc188918af18591852186b18351843186918631891187818b0ff
 (ScriptFailure (TypecheckError "Type mismatch at () in term\n '[\n [\n {\n (abs\n GHC_Tuple_Unit\n (type)\n (lam\n GHC_Tuple_Unit\n GHC_Tuple_Unit\n (lam\n match_GHC_Tuple_Unit\n (fun GHC_Tuple_Unit (all out_GHC_Tuple_Unit (type) (fun out_GHC_Tuple_Unit out_GHC_Tuple_Unit)))\n GHC_Tuple_Unit\n )\n )\n )\n (all out_GHC_Tuple_Unit (type) (fun out_GHC_Tuple_Unit out_GHC_Tuple_Unit))\n }\n (abs\n out_GHC_Tuple_Unit\n (type)\n (lam case_GHC_Tuple_Unit out_GHC_Tuple_Unit case_GHC_Tuple_Unit)\n )\n ]\n (lam\n x\n (all out_GHC_Tuple_Unit (type) (fun out_GHC_Tuple_Unit out_GHC_Tuple_Unit))\n x\n )\n ]'.\nExpected type\n '(fun * *)',\nfound type\n '(all out_GHC_Tuple_Unit (type) (fun out_GHC_Tuple_Unit out_GHC_Tuple_Unit))'"))
```

**Comment by kwxm** [comment]
The redeemer had type () and the validation process was failing with a type error.  I think this is because `runScript` in `Ledger.Scripts` expects a redeemer which can be applied to a list of data scripts and the redeemer was just `()`.  This modifies the redeemer to accept a `Sealed` `HashedDataScript` but just throw it away.  This now appears to work correctly in the playground.

**Comment by j-mueller** [comment]
This is fixed.

**Comment by mrhwick** [comment]
That change needs to be deployed or something. The playground at https://prod.playground.plutus.iohkdev.io/ still has this bug in the vesting scripts.
