### ISSUE TITLE
Investigate using MAST for Plutus Core

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1592]
MAST (Merkelized Abstract Syntax Trees) might save us a lot of space, since it allows us to prune "unused" parts of the program before sending it.

We should investigate how big the savings are.

---

Broad implementation plan:
1. Merkelized version of PLC AST: with hashes at each node.
2. Prunable, merkelized version of PLC AST: nodes can be ommitted and only the hash provided, evaluation, typechecking etc fail if they try to access a missing node.
3. Pruning: evaluate a (already merkelized?) AST, track which nodes are untouched, prune them.
4. Compare vs other approaches:
    - Try pruning just terms, compare to not pruning, maybe compare to compression.
    - Try pruning type nodes, compare to type erasure.
    - Try pruning name nodes, compare to name stripping.

Seems like there's some programming niceties to be done if we want to do this in a nice composable way, but for an experiment we could probably just alter the PLC AST so it's always merkelized.

---

MAST references:
- https://blockstream.com/simplicity.pdf
- http://www.mit.edu/~jlrubin/public/pdfs/858report.pdf

MPJ thoughts:
- Need to make sure that the hash of the non-merkelized PLC AST is the same as of the merkelized one.
    - Means we probably can't keep doing our current hashing strategy, which is to just hash the serialized bytes (I think?).
- Hashes take space, need to be careful we don't make things worse!
    - For the prunable merkelized AST we probably want to only keep the hashes for nodes that are pruned - the others can be recomputed.
    - We could also just not prune nodes that are < hash size (when serialized...).
- Maybe we should benchmark evaluation speed too? I don't expect it to make much difference, but it would be nice to check.

**Comment by kwxm** [comment]
As an experiment I tried adding a 32-byte SHA256 hash to every node in the ASTs for the sample contracts, including types and names.  That increased the total size by a factor of 15-17, taking all of the contracts well over 1GB (and some to almost 3GB).  I don't think we want to do that.

However, I'm not sure why you _would_ want to do that: either you trust the AST, in which case you don't need the hashes, or you don't trust it, in which case you'll have to recompute them all anyway in order to check that the overall hash is the one you're expecting.

My inclination is to introduce a new term `Prune <hash of pruned subtree>`.  I think that would allow you to compute the hash of the complete tree by computing hashes for the parts that you're actually going to run and collecting the hashes of the missing parts from `Prune` nodes.  During execution the evaluator should fail if it ever runs into a prune.

A possible downside to the Merklisation idea is that it may save space but it would probably require a great deal of on-chain hash computation, which could be expensive.  We may have to do some measurements to see how increased computation costs compare with reduced storage/transmission costs.

I think we probably want to discard types and textual names for on-chain evaluation: the figures at https://github.com/input-output-hk/plutus/blob/master/docs/plutus-core/Erasure-Merklisation.md show that this gives significant space savings and I'm not sure that there's any convincing reason to keep them, since you can very easily compare an erased on-chain AST with a full off-chain one to make sure that the former was obtained from the latter.  Maybe a problem is that we'd then have two versions of each validator, and somewhere it would have to be specified exactly what was going on.

**Comment by michaelpj** [comment]
> My inclination is to introduce a new term Prune <hash of pruned subtree>. I think that would allow you to compute the hash of the complete tree by computing hashes for the parts that you're actually going to run and collecting the hashes of the missing parts from Prune nodes. During execution the evaluator should fail if it ever runs into a prune.

Yes, exactly. We indeed don't need to have hashes for things we can recompute!

> I think we probably want to discard types and textual names for on-chain evaluation

I think erasure is still in the air. Manuel still wants to try the version where we merkelize away the types (although I think this will make things worse). Ideally I'd like to get a picture of all of these operations as they interact with each other! (Although that's a combinatorially increasing amount of work...)

**Comment by michaelpj** [comment]
The Marlowe folks pointed out to me that we could also Merkelize `Data`, which potentially saves us a bunch of space if it gets big. Slightly unclear how to wire this up, though.

**Comment by kwxm** [comment]
See https://github.com/input-output-hk/plutus/tree/master/docs/plutus-core/Merklisation for the results of some experiments.

**Comment by kwxm** [comment]
I think I'll close this now.  Conclusion: simplifying and compressing the AST is helpful, Merklisation isn't.  

It might be worth almalgamating the results into a single PDF now that they're complete.
