### ISSUE TITLE
core-to-plc: Can't compile pattern match on ByteString literal

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#1737]
Trying to compile

```haskell
bytestringMatch :: CompiledCode (Builtins.ByteString -> Bool)
bytestringMatch = plc @"bytestringMatch" (\case { "abc" -> True; _ -> False})
```

fails with

```
Exception: Error: Reference to a name which is not a local, a builtin, or an external INLINABLE function: Variable Data.ByteString.Lazy.Internal.eq
               No unfolding
```

Test case: https://github.com/input-output-hk/plutus/commit/fc9603c29fcbd184c28c2b31d00a2586280c520e

(this was originally reported in #1732 but it's not a Playground issue per se)

**Comment by michaelpj** [comment]
Literal patterns are explicitly not supported. The plugin should throw an error for that, but apparently this got turned into an equality before we could, and that uses the normal Haskell `Eq`.

You can use guards, though, that should work.

**Comment by michaelpj** [comment]
But worth me looking into this to see if I can make the error better.

**Comment by michaelpj** [comment]
Notes:
- For *overloaded* literals, GHC compiles a "guarded case expr" i.e. it puts the equality check in. it is *not* a literal pattern, literal patterns are only for unboxed literals (apparently). Possibly real literal patterns appear after inlining.
- This happens in the desugarer, so we have no hope of seeing the AST without it.

I think what I'm going to do is add some special errors for uses of the `Eq` methods, since they seem to be especially common.

**Comment by michaelpj** [comment]
Except our very gentle simplification pass already inlines the `==` methods, so we can't spot them. Even though we set inlining to off :man_shrugging: 

Maybe it's time to try pulling in https://gitlab.haskell.org/ghc/ghc/merge_requests/1230 as a patch for our GHC? That would have the cost of making things really not work for people building our stuff with a non-nix-provided GHC, which I'm reluctant to do.

**Comment by j-mueller** [comment]
> That would have the cost of making things really not work for people building our stuff with a non-nix-provided GHC

How large is that cost really?

If you just want to write a smart contract (no/little Haskell experience) the barrier to working with our stuff is already pretty high. Someone in that group has to set up the tooling in any case, and whether that tooling is nix or stack/cabal/GHC platform/... doesn't make a big difference so it might as well be nix. So I'd say the added pain of having to use a patched GHC is not going to change the decision for or against Plutus.

I think this would primarily affect people who want to contribute to the code base but aren't using nix. And only until 8.10.1 (if I read this correctly, the merge seems to have failed?)

**Comment by michaelpj** [comment]
> How large is that cost really?

I was thinking more for us as developers. I think e.g. stack still manages its own GHCs and will use them, so that won't work.

> if I read this correctly, the merge seems to have failed?

They have a weird merge bot thing like bors, so it did actually go in.

----

Also, I've remembered that this doesn't help us, since the unfoldings from other modules get lightly simplified, so the problem would just occur one step removed anyway.

**Comment by j-mueller** [comment]
Ok. For the issue at hand it's fine to say that it's not supported at the moment.
