### ISSUE TITLE
cabal.project (and freeze) file

### ISSUE THREAD

**Issue by angerman** [input-output-hk/plutus#1742]
I have two requests:

1. can we add comments to the cabal.project file?
    - Why do we set `optimization: 2`? I trust there is a reason, but could we write that down?
    - Why do we need `max-backjumps: 160000`? git blame tells me cabal's solver is silly. Ok.
    - Why do we need `allow-boot-library-installs: true`?

2. can we drop the freeze file in favour of setting a hackage [index-state](https://www.haskell.org/cabal/users-guide/nix-local-build.html#cfg-field-index-state)? Preferrably one that is in haskell.nix 😁

**Comment by michaelpj** [comment]
> Why do we set optimization: 2? I trust there is a reason, but could we write that down?

Not AFAIK. That's always been there...

> Why do we need max-backjumps: 160000? git blame tells me cabal's solver is silly. Ok.

At some point it didn't work without raising the limit. This made it work.

> Why do we need allow-boot-library-installs: true?

No idea.

> can we drop the freeze file in favour of setting a hackage index-state? Preferrably one that is in haskell.nix

The `stack.yaml` is the source of truth. We don't have bounds in all our cabal files because we're lazy. So we need some way to ensure that people are using the same set of dependencies as the stackage snapshot. The freeze file seemed like a good way of doing that :man_shrugging: 

AFAICT setting an index-state is not sufficient for that: it might be in combination with a freeze file, or actually putting in bounds.

(You may recall this thread: https://input-output-rnd.slack.com/archives/C21UF2WVC/p1573703069344900)

--------------

Meta-point: I'm guessing this is for `haskell.nix`. I'd suggest using `stack-to-nix` for that if possible, since.

**Comment by michaelpj** [comment]
I'll try removing some of the possibly-redundant settings and see if anything breaks.

**Comment by michaelpj** [comment]
Tidied the project file here: https://github.com/input-output-hk/plutus/pull/1754

**Comment by michaelpj** [comment]
I don't think there's anything else to do here. Feel free to reopen if we really do need to get rid of the freeze file.
