### ISSUE TITLE
Smart contracts and rollbacks

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1789]
We need to work out how contracts should interact with rollbacks. We don't want rollbacks to cause contracts to get into unexpected (or even unrecoverable) states, especially since rollbacks are common in Praos.

Some key facts:
- Transactions that are rolled back are put back into the mempool, i.e. may be re-applied.
- A rollback always transitions from the old chain to a new chain of a longer length.

The first fact is the one that makes our lives difficult. Since our contracts are stateless and based on the series of events they've seen, we can roll that series back to the rollback point and replay with the new chain. *However*, some of the transactions that were produced the first time might still be around, which can cause issues.

To see this, consider the following program:
```
if p(utxo_set) 
then pay_to_using(x, a, y) -- call the transaction this produces A
else pay_to_using(x, b, w) -- call the transaction this produces B
```
Suppose we are running this and we take the first branch, submitting transaction A. Now we have a rollback, and when we replay we take the *other* branch, submitting transaction B. But transaction A is still in the mempool, so both can get applied! Now our contract has done the side-effects from both branches, which is pretty bad (in particular, it's potentially spend twice as much money as it was supposed to).

We really want some way to avoid these kinds of issues, ideally automatically and without requiring our contract authors to do anything clever.

---

MPJ thoughts:

A tactic we can use is to exploit dependencies between transactions. In a simple version, if A and B spend a shared output, then only one of them can be applied. But that can still leave us in the *program* branch where we're supposed to submit B, but it fails and A is applied instead. Also bad.

However, we could perhaps go further: suppose we refuse to allow adding a transaction to the pending set unless it's dependent on all of the transactions already in there (otherwise you can wait until that one is confirmed, then you can submit the next one). 

This ensures that there is always a linear ordering of the pending transactions. Then when we rollback we do the following:
- Wait for all the now-pending transactions to be either applied or fail to apply.
- Prune back our event history to the point where the last transaction was successfully applied.
- Carry on as normal.

So suppose we have submitted transactions A, B, and C in some event stream `[.., A, .., B, .. ,C, ..]`, and all of these have been confirmed (but not `k`-confirmed). Then they are all rolled back.
- A, B, and C are all now in the pending set.
- By hypothesis, they have a linear dependency ordering.
- We wait, and A and B are confirmed again, but C is rejected.
- We prune the event stream to `[.., A, .., B ]` and resume.

How does this avoid the problem above? The answer is that because we replay the *old* even stream up to the last transaction that gets reapplied, we're guaranteed to be in the same program branch. So it's as though our contract makes the "right decisions" for the "wrong reasons" since some of those events may not reflect reality in the new chain. 

This may still result in odd behaviour: the event that caused us to submit a transaction may not occur second time round, but we're still committed to doing it. But this is a problem that can affect even humans - the right solution here is to wait a sufficient period after the event you care about that the risk is small (and I think we can require programmers to deal with this).

**Comment by j-mueller** [comment]
Here's one to encode transaction dependencies in the current system:

* Suppose we have transactions A, B and C. A should always go on the chain but B and C are mutually exclusive.
* Before we submit A, we add two things to it (resulting in a transaction A*): (1) A monetary policy script that forges a single (non-fungible) token, checking that its transaction spends all of A's inputs and produces all of A's outputs, and (2) a public key output that holds the token. Then we submit A* instead of A.
* Then we change B and C: We add a similar MPS like we did with A, producing a token if the transaction has all of the inputs and outputs of B (or C, respectively). But this MPS also checks that the token we produced in A* is spent by B* or C*. Since there is only one token we ensure that only one of B* and C* gets validated.

The nice thing about this is that it doesn't depend on A, B and C sharing any inputs. In practice, B* and C* will probably share the output that holds the token of A*, but this is not required for the scheme to work.

Downside is that it relies on a certain property of transactions, namely that every script that accepts A should also accept A*. (if you use the WIP constraints interface then you get this property automatically :) )

On the client side (program branch) we could use the backtracking effect to keep track of all the possible branches, and we use the definitively confirmed transactions (greater than k blocks ago) to prune the branches.

**Comment by michaelpj** [comment]
> Here's one way to encode transaction dependencies in the current system

Isn't this just making everything into a state machine? I guess it's the other half of that: we say every contract has to have an *identity token*, but doesn't have to be a state machine per se. Then you can always ensure that there's a single thread to follow. That's a simpler way of getting the linearity condition I want.

Another thing: if we have a transaction A that depends on an existing transaction, and a transaction B that doesn't, we can submit both A and B by.... using batch transactions! This is a nice use I hadn't thought of: it makes the combined transaction have the union of the dependencies, which is pretty handy here (it would have to be replayed as a batch after a rollback for this to work, though).

**Comment by j-mueller** [comment]
Yeah it's independent of the rest of the transactions, it doesn't even require them to have any script outputs.

I suppose my main point is that the client code should reflect the fact that the last k blocks of the blockchain are really a tree, instead of trying to collapse it into a single stream from which events get deleted

> using batch transactions

With the tokens you can bind together transactions that happen in different slots, I'm not sure whether that would be possible with batch transactions. 

On the other hand, batch transactions (presumably) allow you to have an invalid ledger state in the middle, which you can't do with the tokens. Also, in a batch transaction, failure to validate a later transaction would invalidate all the earlier transactions in the batch, whereas in the token scheme the only way earlier transactions can be invalidated is if a rollback occurs and they don't get validated again.

**Comment by michaelpj** [comment]
> I suppose my main point is that the client code should reflect the fact that the last k blocks of the blockchain are really a tree, instead of trying to collapse it into a single stream from which events get deleted

I'm not sure how easy that is. What I'm trying to do is make sure that we always "commit" to the branch of our *program*'s execution that we took "in the previous universe" (before the rollback). That way we ensure that our program state is synchronized with what happens on the chain.

---

Here's an example that maybe shows why I like the batch transactions. Suppose we have a contract that uses *two* state machines (A and B). We want to take an action where we advance A, and if that succeeds, we then advance B. But they probably don't share a "thread", so we're opening ourselves up to a rollback replaying the B transaction but not the A one. And this is even though we're using state machines.

Now, we could force the contract to have a single token thread that forces serialization of these, and that might well work. But an alternative is to just put them both in a batch transaction, which effectively binds B to A's state thread, allowing you to use that one to enforce serialization.

I don't think they solve the problem entirely, but I think they might be a useful part of the toolbox.

**Comment by j-mueller** [comment]
I agree - I'm not arguing against batch transactions (they'd still be good to have), I just don't think they are enough to deal with rollbacks on their own.

**Comment by jmchapman** [comment]
(I have been going through github notifications using their new handy mobile app)

In the example, I would hope that A should no longer validate and be rejected, the property of the utxo no longer holds. Do you have a more specific example in mind?

**Comment by michaelpj** [comment]
There are a lot of examples using A and B here, which one are you referring to ? :)

**Comment by jmchapman** [comment]
The first one:
```
if p(utxo_set) 
then pay_to_using(x, a, y) -- call the transaction this produces A
else pay_to_using(x, b, w) -- call the transaction this produces B
```
