### ISSUE TITLE
Do we handle stack overflow properly in the machine?

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1831]
I was explaining to someone that we have a stack in the machine, and I realised that I didn't know if we handle "stack overflow"s of either of two kinds:
- The machine stack gets very large. 
    - This would manifest itself by the heap blowing up, I guess.
- The Haskell stack gets very large.
    - This could manifest itself with a Haskell RTS error, I guess.

Both of these should be somewhat controlled by resources, since we make people pay for using the machine stack, and I don't think we do unbounded Haskell recursion without adding machine stack frames.

However, if someone, say, supplies a very large amount of resources and tries to spend them as efficiently as possible to blow one of the stacks... what happens?

**Comment by kwxm** [comment]
Ill-behaved PLC programs can certainly cause problems. For example,  when I was experimenting with the lazy evaluator I had a programs which used the standard Y combinator, and if I ran them on the CEK machine it would use up all my memory (8GB) very quickly and disable my machine, requiring a reboot.  I asssumed that this problem would go away when we finally started monitoring costs, but perhaps we should check.  

We'll presumably be charging for builtin evaluation based on the size of the inputs, so that should stop people directly creating large objects on the heap (12345^12345 should be very expensive, for example).  If that works properly then the main problem is (I think) performing too many execution steps, leading to a large CEK stack.  We might be able to guard against this kind of thing by charging non-linearly for CEK stack usage:  have the cost increase in steps as the stack grows (ie, with the number of successive calls to `evaluateCek`), or quadratically or something.

This brings up another issue which I've been vaguely wondering about.  Are we actually going to use the CEK machine on the chain?  The throughput of the chain is a crucial factor, and PLC execution may have a substantial effect on that.  We should make our evaluator as efficient as we can.

**Comment by effectfully** [comment]
> The Haskell stack gets very large.
> This could manifest itself with a Haskell RTS error, I guess.

I think we should test what happens in that case, because the implementation really should be tail-recursive (not that I was thinking of that when I was writing it) and if it's not, it's a bug (unless I'm missing something). Luckily, [testing for such stack overflows](http://neilmitchell.blogspot.com/2015/09/detecting-space-leaks.html) is easy.

> This brings up another issue which I've been vaguely wondering about. Are we actually going to use the CEK machine on the chain? The throughput of the chain is a crucial factor, and PLC execution may have a substantial effect on that. We should make our evaluator as efficient as we can.

What's with that hypothesis that most of the time is going to be spent on hashing, by the way?

**Comment by michaelpj** [comment]
> This brings up another issue which I've been vaguely wondering about. Are we actually going to use the CEK machine on the chain? The throughput of the chain is a crucial factor, and PLC execution may have a substantial effect on that. We should make our evaluator as efficient as we can.

Yes. This is definitely something we need to work on before launch.

> What's with that hypothesis that most of the time is going to be spent on hashing, by the way?

Essentially none of our scripts do hashing or cryptographic operations, because we've mostly adopted clever strategies that piggyback off stuff that the slot leader does.

However, I think some approaches to oracles may result in us wanting to do some signature verification.

So I think that the majority of scripts won't do much hashing or crypto, but some will.

**Comment by kwxm** [comment]
> I think we should test what happens in that case, because the implementation really should be tail-recursive (not that I was thinking of that when I was writing it) and if it's not, it's a bug (unless I'm missing something). Luckily, [testing for such stack overflows](http://neilmitchell.blogspot.com/2015/09/detecting-space-leaks.html) is easy.

I did implement a CPS version of the CEK machine when I was investigating laziness and stuff. That was quite tricky to get right because if you made any mistakes it was hard to see what was going on. I don't think the behaviour was significantly different from the original machine. I guess you just exchange the explicit stack for a chain of continuations in the Haskell heap.  It might be worth having another look at this kind of thing now that we're closer to deployment and have realistic programs.

**Comment by michaelpj** [comment]
> I did implement a CPS version of the CEK machine when I was investigating laziness and stuff. That was quite tricky to get right because if you made any mistakes it was hard to see what was going on. I don't think the behaviour was significantly different from the original machine. I guess you just exchange the explicit stack for a chain of continuations in the Haskell heap.

Yeah, this doesn't obviously seem like a win. I think the ideal case would be that we have a tail-recursive implementation: then hopefully we aren't using any (Haskell) stack. Although my knowledge of the Haskell RTS isn't strong enough to be confident of that.

**Comment by kwxm** [comment]
>  Although my knowledge of the Haskell RTS isn't strong enough to be confident of that.

This is my problem with Haskell (or one of them, anyway). If I'm programming in OCaml for instance then I know exactly what's going on at runtime.  With Haskell it's all a bit of a mystery to me.

I wonder if we can have a completely tail-recursive implementation.  It seems to me that we _have_ to remember the surrounding context somewhere (eg, if you're evaluating an argument you have to remember what it's an argument _for_) and that's always going to take up some space.  Maybe that's because I'm fixated on the CEK strategy: there may be more efficient ways to evaluate things.

**Comment by michaelpj** [comment]
>  It seems to me that we have to remember the surrounding context somewhere (eg, if you're evaluating an argument you have to remember what it's an argument for) and that's always going to take up some space.

For sure: this is in the CEK machine's stack (which is a list on the *Haskell* heap, and so not in the *Haskell* stack).

**Comment by effectfully** [comment]
> It seems to me that we have to remember the surrounding context somewhere (eg, if you're evaluating an argument you have to remember what it's an argument for) and that's always going to take up some space.

Yes, but that takes up space on the heap, because we explicitly implement the stack via `type Context = [Frame]` rather than rely on the Haskell's stack?
