### ISSUE TITLE
How should we parse PLC?

### ISSUE THREAD

**Issue by effectfully** [input-output-hk/plutus#1844]
In the presence of extensible builtins parsing becomes harder. We essentially need to poke a hole in the parser to make it accept subparsers for builtins. `happy` doesn't seem appropriate in this case. Should we reuse the IR's parser? `happy` should be faster, but we don't really parse anything in prod (there we use binary deserialization), so who cares.

**Comment by michaelpj** [comment]
I can't think of any reason why we shouldn't do this, other than speed. And I can't think of any situation where we want to parse PLC except in tests: as you say, in all other situations we either generate the AST in-memory, or we deserialize it from binary.

It *would* be nice to be able to still give a sensible grammar in the spec, but I think that's fine with the approach you suggested here: we'll just have to say that there's a "hole" in the grammar for builtin constants.

**Comment by effectfully** [comment]
I've managed to update the current parser to the new machinery by using a hardcoded universe (that includes `integer` and `bytestring`). So this doesn't seem to be a high-priority task.

**Comment by kwxm** [comment]
I did look at the existing parser and it didn't look terribly complicated.  As pointed out though, it's probably not easy (or even possible) to make it so that users can plug in new stuff to handle new builtins (specifically, literal constants) that they've implemented themselves, and this is something that you could do with parser combinators (modulo introducing stuff that conflicts with the existing syntax).  

I agree with the previous comments that we don't use the parser very much and it's probably not very pressing to do anything about this issue right now.  The only thing that I can think of at the moment is that having an extensible parser might be useful to external people who are implementing new builtins and want to test/debug them.

**Comment by kwxm** [comment]
I may actually take a look at this when I have some spare time.  The `plc` parser can't parse textual dumps of validators because they involve variables with the same names as builtins (for example, the `equalsInteger` builtin is wrapped in a lambda of the same name and always called via that).  All of the builtin names are keywords in the parser, which causes syntax errors if you use the names for anything else.  I'm pretty sure that there's no real need to do this: the grammar's so rigid that we can always tell from the context what's a builltin name and what isn't.  In fact, I suspect that we don't need any keywords at all.

**Comment by kwxm** [comment]
Also, Plutus validators involve some extended builtins, like the type `(con string)`.  The parser doesn't know about these, so it fails when it finds them.

**Comment by kwxm** [comment]
Builtin-related things appear in three contexts in the grammar:

   * Application of built-in functions: `(builtin <name> <types> <args>)`
   * Built-in types: `(con <typename>)`
   * Literal constants from built-in types: `(con <some special syntax>)`

I think we could deal with the first two in the happy parser quite easily, by passing the parser tables mapping function and vairable names to appropriate chunks of PLC AST.  The context will always tell us when we need to look up a name, and which table to use.

Parsing literal constants would be more difficult.  Could we just do this by using `read`?  I think the problem there would be knowing what type of constant we're expecting.  A cheap but not terribly elegant way of doing this might be to require the first character (or the first few characters) of the constant to identify the type uniquely: `# ...` for bytestrings, `[-+0-9]...` for integers, `"...` for strings, `[..` for lists, etc (this could be tricky if we have complicated builtin objects containing complex and possbily polymorphic subobjects).  You could then pass in a function that switches on the initial character(s) to parse constants of the appropriate type.  An alternative might be to pass in a small applicative parser that deals with constants.

Does this sound plausible?  It's far from ideal, but maybe we could get away with something hacky in the short term since the parser isn't a vital part of the Plutus infrastructure.  

A problem is how to tell the `plc` command which set of builtins it should be using.  You'd ideally want to start it up with an option saying "use this particular set of extended builtins", but I can't immdiatel think of any way of doing this other than coding the available choices into the command.

**Comment by michaelpj** [comment]
> An alternative might be to pass in a small applicative parser that deals with constants.

Yes, I think something like this is the way. I imagine that you might have to pick a "key" for your builtin type that will be included after `con` that tells us what type to parse. This would have to be distinct from all other keys in use, of course.

Not very nice, but I can't see a nicer way.

> A problem is how to tell the plc command which set of builtins it should be using. 

I don't think we can really configure this nicely from the command line. So I think it should just use whatever our "default" universe is.

**Comment by effectfully** [comment]
> I don't think we can really configure this nicely from the command line. So I think it should just use whatever our "default" universe is.

I think, we can. Quoting a slack discussion with Kenneth:

> A term can be evaluated whenever the universe that it's defined in implements certain type classes. So currently you have to define a universe beforehand in order to evaluate anything.
> It'll be possible to relax this restriction and create universes on the fly. So you'll just have to implement a mapping from the name of a type to the type itself (using an existential data type or CPS). E.g.
>
> ```haskell
> withParsedType :: Text -> (forall a. Proxy a -> r) -> r
> withParsedType "string" k = k (Proxy @String)
> <...>
> ```
>
> and compose several parsed types into a single universe via a provided function.

"Creating universes on the fly" is basically sticking all the types into the same n-ary sum type. Like [this one](http://hackage.haskell.org/package/fastsum-0.1.1.0/docs/Data-Sum.html#t:Sum) for example.

But I think we should just stick to the default universe until we actually need to configure something.

**Comment by kwxm** [comment]
Closed in favour of SCP-429.
