### ISSUE TITLE
[Plutus Playground] Simulator not working as expected

### ISSUE THREAD

**Issue by Daniel-R-Afonso** [input-output-hk/plutus#2850]
Diagnostic info:
- I was using the:
    - [x] Plutus Playground
    - [ ] Marlowe Playground
- Link to gist with saved setup that reproduces the issue: 
https://gist.github.com/Daniel-R-Afonso/afd0a9c466895eca7f3477ec0c17d26d

Steps to repruduce:

Go to https://playground.plutus.iohkdev.io/
From Demo files click on **Starter**;
Copy and paste my gist;
Click on compile;
Click simulate;
Close all the predefined tabs (Publish/Redeem,Pay To Wallet);
Create the simulation as below (Simulation 2);
![Screen Shot 2021-03-11 at 11 24 00](https://user-images.githubusercontent.com/3138127/110780164-4fa8d980-825c-11eb-80b0-11b0fd1f4bc1.png)
Click evaluate;
Verify that the script has 0 ada being sent instead of the sumulation value (10).

**Comment by ElGatoLoco** [comment]
I managed to get it working by defining custom PublishParams and RedeemParams https://gist.github.com/ElGatoLoco/4dd94b60e28aec42868e1a9bf1e5ce5b. 

Anyway, the example is a bit misleading as it states that the only necessary change is to provide implementation for the validator. Also, it's kinda disappointing that the code compiles successfully.

**Comment by james-iohk** [comment]
Hi @Daniel-R-Afonso, sorry for the delay in getting back to you on this. There have been a few changes to plutus since you raised this and I have confirmed this issue can no longer be reproduced. However, the [playground](https://playground.plutus.iohkdev.io/) has not been updated in a while so it is still reproducible here, this will be updated in due course. Meanwhile, we recommend you use a local instance of the playground with a recent checkout of plutus, e.g. 476409eae. Alternatively, in our [staging environment](https://staging.plutus.iohkdev.io/).
Please note, there is now a 10 lovelace fee for every transaction in the playground so you will want to increase wallet starting amount to minimum of 20.
