### ISSUE TITLE
Add field validator to slot input to prevent warnings/confusion - Marlowe blocks editor

### ISSUE THREAD

**Issue by BeksOmega** [input-output-hk/plutus#2896]
Diagnostic info:
- I was using the:
    - [ ] Plutus Playground
    - [X] Marlowe Playground
- Link to gist with saved setup that reproduces the issue: https://gist.github.com/BeksOmega/f2d521d538c1494b2993eedba18a7e44

![bad-slot-values](https://user-images.githubusercontent.com/25440652/112348560-2d17b700-8c85-11eb-9755-69d256803934.png)

### Description

The Marlowe blocks editor allows you to enter bad/confusing values into the "slot" field. For example, it allows you to enter:
  * Negative slot values - This creates a warning
  * Non-increasing slot values - This creates a warning
  * Decimal slot values - This acts as a SlotParam (which is confusing)
  * "Arithmetic" values - This acts as a SlotParam (which is confusing)

The advantage of blocks-based programming is that we can prevent these situations from every occuring, by not allowing the input field to accept these values.

### Suggested Fix

I suggest adding a [custom field validator](https://developers.google.com/blockly/guides/create-custom-blocks/fields/validators) to the slot text input field which only allows increasing natural-number values, or pure alphabetical strings to be entered. This would prevent confusing or error producing situations from occuring.

Note that you would likely still want to statically-analyze the slot values, because the user could (for example) rearrange blocks so that the values become non-increasing, which the field validator would not catch. You could prevent some of these problems by adding an [event listener](https://developers.google.com/blockly/guides/configure/web/events) that re-validates the slot value when the blocks are moved, but it's still probably best to do the static analysis, just in case.

**Comment by palas** [comment]
Thank you for your feedback and the custom field validator idea. We will soon be looking at using times instead of slots so we will have to rethink how timeouts are input in Blockly. And I am starting to see how having combined SlotParam and normal timeouts may be quite problematic, so maybe we should separate them too

**Comment by BeksOmega** [comment]
> We will soon be looking at using times instead of slots so we will have to rethink how timeouts are input in Blockly.

Ooo that sounds really cool! I hope the investigation goes well :D

Related to this: Do you have a versioning system for your blocks-representation? Blockly does not (as yet) provide one, so I love looking at the solutions other applications have built.

> And I am starting to see how having combined SlotParam and normal timeouts may be quite problematic, so maybe we should separate them too

I like the idea of separating them out! After doing some more testing I found another issue with using the single field, which is that numeral strings don't round-trip correctly from text->blocks->text.

For example this contract:
```
When
    [Case
        (Deposit
            (Role "role")
            (Role "role")
            (Token "" "")
            (Constant 1000)
        )
        Close ]
    (SlotParam "1")
    Close 
```

Turns into this after round-tripping through the blocks view:
```
When
    [Case
        (Deposit
            (Role "role")
            (Role "role")
            (Token "" "")
            (Constant 1000)
        )
        Close ]
    1 Close 
```

This also brings up a problem with the field-validator idea, which is that if it were applied, the text-representation would be more permissive than the blocks-representation. For example this would still be valid text-based Marlowe:
```
When
    [Case
        (Deposit
            (Role "role")
            (Role "role")
            (Token "" "")
            (Constant 1000)
        )
        Close ]
    (SlotParam "param + 1")
    Close 
```

But if the proposed validator was applied to the field, it would not be able to accept "param + 1".

So I guess the validator solution doesn't work unless you can also constrain the text-representation :/

**Comment by palas** [comment]
Sorry, just saw your post

> I like the idea of separating them out! After doing some more testing I found another issue with using the single field, which is that numeral strings don't round-trip correctly from text->blocks->text.

Precisely, that is what I was thinking about. As it is, you cannot have a numeric `SlotParam` in Blockly, so they are no longer equivalent representations. It seemed like a clever hack at first, but it is problematic

> This also brings up a problem with the field-validator idea, which is that if it were applied, the text-representation would be more permissive than the blocks-representation.

Yes, since we allow any string in `SlotParam`, I don't think we can validate that, but we can validate it is a number (or a date) if we have proper separation between `SlotParam` and `Slot` in Blockly, I am looking into that now

> Related to this: Do you have a versioning system for your blocks-representation? Blockly does not (as yet) provide one, so I love looking at the solutions other applications have built.

We do not have a versioning system for Blockly or for Marlowe. At the moment we actually store the Marlowe representation of the Blockly workspace, so we would not have to worry about Blockly versions changing, but it also means we only save blocks that are connected to the CONTRACT block and that loose blocks and their positions would get lost, which is not ideal.

We haven't worried so much about versioning so far because we are in prototype stage yet, but when we go on-chain we will have to start thinking about it

**Comment by palas** [comment]
Fixed by https://github.com/input-output-hk/plutus/pull/3021
