### ISSUE TITLE
Feature-request: Lookup transactions by id as contract effects.

### ISSUE THREAD

**Issue by KtorZ** [input-output-hk/plutus#3089]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[x] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Describe the feature you'd like

I'd like to be able to run an extra contract effect in off-chain code to lookup any arbitrary transaction from its id. The framework already provides `utxoAt` for looking up funds in the UTxO, but I'd like to query historical data of some past transaction. More precisely (although it doesn't make the problem any simpler), I am really interested in the inputs of a transaction that originated a particular UTxO I have a reference to. 

## Describe alternatives you've considered

To cope with this so far, I've been keeping track of the relevant past transaction outside of the contract code, and passing them to the contract endpoint as inputs. Yet, this is very much an abstraction leakage from my contract's perspective; I'd prefer clients not to have to do this extra state management. 

## Additional context / screenshots

N/A

**Comment by j-mueller** [comment]
Asking for arbitrary transactions is a bit too powerful, because we don't want to keep the entire blockchain in our database. If you need that you have to run your db outside of the PAB.

We are going to overhaul the chain index however, to keep more information for `TxOutRef`s that are in the utxo set. So if your UTXO is still unspent you could get the tx that produced it from the chain index.

**Comment by KtorZ** [comment]
> So if your UTXO is still unspent you could get the tx that produced it from the chain index.

That'd be sufficient for my use-case :+1: , thanks.
