### ISSUE TITLE
Why use both CurrencySymbol and TokenName to represent a token in Value?

### ISSUE THREAD

**Issue by longngn** [input-output-hk/plutus#3105]
I'm developing a Plutus Dapp and stumbled upon this.
Is there any reason for this? And why is ADA's both CurrencySymbol and TokenName are just empty byte string?

**Comment by ak3n** [comment]
That's because the Plutus Platform supports multi-currencies. ADA is a primary currency but not alone.

Citing ["Plutus Techincal Report"](https://hydra.iohk.io/job/Cardano/plutus/linux.docs.plutus-report/latest/download-by-type/doc-pdf/plutus):

> The currency name tells what controller should forge or destroy the tokens. Each currency is controlled by Monetary Policy Script. The token name separates different classes of tokens within the currency. Only tokens of the same currency and token name are fungible with each other.

> Hence one could use a currency to track items in a game: different kinds of items would have different token names, and an asset bundle could consist of e.g. 3 swords, 7 hats, and a cheesecake.

> For example, NFTs can be implemented as token classes within a currency whose supply is limited to a single token.

Since ADA is the primary currency it has empty CurrencySymbol and TokenName being something like a center of coordinate system.
