### ISSUE TITLE
PAB - production workflow

### ISSUE THREAD

**Issue by Benjmhart** [input-output-hk/plutus#3185]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[x] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Summary

we're currently using PAB backend to support our application and it's working well, i had a question about the generated wallets that PAB uses to make transactions and how they fit into the production usecase of PAB as a website backend.

In general, should we expect to be generating a wallet in pab for each of the users on our frontend? or should we expect to have PAB integrate with a browser-based wallet via something like [cardano-wallet-js](https://github.com/tango-crypto/cardano-wallet-js) ?

## Steps to reproduce
N/A - how-to issue
## Expected behavior
N/A

## System info (please complete the following information):

arch linux

- Plutus version or commit hash
36c8804a6dbaff489249e4e09aa3fd382903edb8
## Screenshots and attachments
N/A

**Comment by ak3n** [comment]
Thanks for the question!

The PAB should use a wallet backend and not create wallets itself. But currently, the PAB uses generated/mock wallets because the Alonzo-capable wallet backend is not available yet. As soon as that is available the PAB will use the real wallet backend (the same that is used for example by Daedalus).

Also, it's might be possible in the future to integrate with light wallets such as [Yoroi](https://yoroi-wallet.com). This is important for scenarios where a centrally hosted PAB is used by many different people. There's no timeline on this yet though.

`cardano-wallet-js` is just a frontend for a [cardano-wallet backend](https://github.com/input-output-hk/cardano-wallet) which still needs to run as a server process somewhere. If there is a wallet server process running somewhere, the PAB will be able to connect to it, at the time of the first release. And it doesn't matter what frontend is used as long as PAB communicates with a wallet backend directly and users free to chose whatever wallet frontend they want.

**Comment by Benjmhart** [comment]
Do we know what the first such backend to support Alonzo will be? Can we be assured this will be available during the testnet period?

**Comment by ak3n** [comment]
There'll be a few testnets. If the question is about Pioneers Testnet, then it looks like backend support will be introduced throughout it's lifetime. For sure there will be backend support for some public testnet.
