### ISSUE TITLE
Faulty rendering of Testing Tutorial

### ISSUE THREAD

**Issue by brunjlar** [input-output-hk/plutus#3238]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[x] *Other* Any other topic (Playgrounds, etc.)

## Summary

The testing tutorial is not displayed correctly when opening it in a browser.

## Steps to reproduce

1. Go to the [testing tutorial](https://github.com/input-output-hk/plutus/blob/master/doc/plutus/tutorials/contract-testing.rst)
2. Observe

## Expected behavior

I'd expect to see a properly rendered page. Instead I see "control instructions" all over the place.

## System info (please complete the following information):

- OS: ArcoLinux
- Plutus commit hash `3ec69796628e58f01f3f08514530da577e263db5`

## Screenshots and attachments

![image](https://user-images.githubusercontent.com/6307039/119129460-3b8d0f80-ba37-11eb-81ca-411b7c90dbde.png)

**Comment by michaelpj** [comment]
The documentation is not intended to be viewed via the Github file browser! Just because Github thinks it can render a random RST file independently doesn't mean it's true :) The rendered documentation site is linked to in the README at the top: https://github.com/input-output-hk/plutus#user-documentation
