### ISSUE TITLE
The local plutus playground auto suggestion feature not working properly

### ISSUE THREAD

**Issue by hhqwerty** [input-output-hk/plutus#3858]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[x] *Other* Any other topic (Playgrounds, etc.)

## Summary
The suggestion show list suggestions with empty texts, but it's still functional

## Steps to reproduce

1: cd path/to/plutus
2: nix-shell
3: cd plutus-playground-client; plutus-playground-server;
4: open new terminal;
5: nix-shell;
6: cd plutus-playground-client; npm run start;
7: open localhost:8009
8: type something to try autocomplete

## Expected behavior

AutoComplete show list of text suggestions

## Actual behavior

AutoComplete show list with blank, even though when I choose an item of the list, it still works ( the suggestion filled data to the editor) 

## System info (please complete the following information):

- OS: Ubuntu
- Version 20.04
- Plutus version or commit hash: 36dcbb9140af0c9b5b741b6f7704497d901c9c65

## Screenshots and attachments
![image](https://user-images.githubusercontent.com/30863277/131991328-93a3216b-1de3-476b-ac0a-3071d324db7c.png)

**Comment by luigy** [comment]
Thanks, I was able to reproduce. This turned out to be a styling issue alone of selectors meant for playground layout accidentally getting applied into the editor suggestion dropdown as well due to a classname collision. Fix awaiting review.

![2021-09-03-133524_1130x1134_scrot](https://user-images.githubusercontent.com/817138/132049188-1a46cd2c-cc1d-4c4c-9226-03a17bb299f7.png)

**Comment by hhqwerty** [comment]
thanks, @luigy. Really appreciate your help
