### ISSUE TITLE
API for data encrypt/decrypt via PublicKey/PrivateKey

### ISSUE THREAD

**Issue by volodyad** [input-output-hk/plutus#4027]
## Area
[] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries

## Describe the feature you'd like

In Ledger.Crypto I do not see any API which allows to encrypt the data via PublicKey,
Would be good to have helper methods a to encrypt the data via Plutus.V1.Ledger.Crypto.PubKey or  Plutus.V1.Ledger.Crypto.PrivateKey and decrypt vice versa

Maybe this methods available in some other modules?  
Or there are examples available how this could be done?

**Comment by ak3n** [comment]
Decrypting anything on-chain doesn't make much sense because it requires you to make your private key public.

If you want to use encryption in the off-chain code, you can just add a dependency on [cryptonite](https://hackage.haskell.org/package/cryptonite) or other library and use the library directly as `PubKey` and `PrivateKey` are just wrappers around `ByteString` and the data is easily available. Examples can be found in https://github.com/input-output-hk/cardano-crypto.

**Comment by volodyad** [comment]
I want to encrypt data with user PubKey, so it is only can be decrypted by party who owns privatekey
