### ISSUE TITLE
Change ordering of arguments to scripts

### ISSUE THREAD

**Issue by L-as** [input-output-hk/plutus#4190]
## Describe the feature you'd like

Often, DApp developers will encounter a need for mutually referencing scripts, e.g.
a validator that references a minting policy that in turn references the validator.

This is obviously impossible due to how hashing works, but if they were both validators,
the solution would then just be to merge them into a single validator, since a script always
knows its own hash.

We can extend this functionality to scripts of different types too, by passing the script
context first. Through this, we can use the exact same script as *both* a minting policy
and a validator. It will inspect the script context (the first argument) to figure out what the
purpose is, and then take either 1 argument or 2 arguments, depending on the purpose.

Currently, this is impossible, because the script context is either the 2nd or 3rd argument,
and there is no easy way of figuring that out from the 1st argument, which might be
either a datum or a redeemer. That is not to say it is impossible, but it requires putting
extra data into the datums and redeemers.

### The concrete change

Currently, scripts are passed the script context last, in pseudo-code:
```haskell
type Validator = Datum -> Redeemer -> ScriptContext -> Bool
type MintingPolicy = Redeemer -> ScriptContext -> Bool
type StakeValidator = Redeemer -> ScriptContext -> Bool # maybe not correct? 
```

I propose it is switched to the following:
```haskell
type Validator = ScriptContext -> Datum -> Redeemer -> Bool
type MintingPolicy = ScriptContext -> Redeemer -> Bool
type StakeValidator = ScriptContext -> Redeemer -> Bool 
```

### Backward compatibility

I'm not sure how you usually deal with these kinds of changes.
I assume you would make the above change for V3 scripts for the next hardfork.

## Describe alternatives you've considered

Technically, you don't need this if you put extra information into the datums and redeemers.

**Comment by michaelpj** [comment]
> We can extend this functionality to scripts of different types too, by passing the script
context first. Through this, we can use the exact same script as both a minting policy
and a validator. It will inspect the script context (the first argument) to figure out what the
purpose is, and then take either 1 argument or 2 arguments, depending on the purpose.

This can only work in untyped Plutus Core, since writing
```
f :: (x: Context) -> ... type that depends on x ...
```
is dependent typing, which we definitely don't have.

As there is essentially no tooling for working with UPLC without going via Typed PLC, I don't find this very appealing.

----

Another potential alternative is to take the arguments in a list. I don't like this much because it complicates the argument passing for the "normal" case in order to support this more unusual case. It's not clear to me that it's worth it.

**Comment by L-as** [comment]
Couldn't you make a typed abstraction for it? E.g.
```haskell
mkValidatorMintingPolicy :: Validator -> MintingPolicy -> Script
```

**Comment by michaelpj** [comment]
Ah I see, have a small untyped wrapper to dispatch to the typed parts. Maybe, but it's untypable, so I guess we'd have to write it directly in UPLC, which I really don't want to do.

**Comment by L-as** [comment]
Would you accept a PR that does this?

**Comment by michaelpj** [comment]
That does what? Changes the order? Definitely not, that's a massive change to the interface and we'd need to think about it very seriously.
