### ISSUE TITLE
Rational has large on-chain function sizes

### ISSUE THREAD

**Issue by kozross** [input-output-hk/plutus#4250]
## Summary

The on-chain sizes for operations over `Rational` from Plutus is surprisingly large, especially when compared to similar operations for `Integer`. While this is unsurprising in itself, the size difference is quite a bit larger than expected, even on operations which shouldn't really need it.

## Examples

These numbers were established by the testing methods [used in `plutus-size-check`](https://github.com/Liqwid-Labs/plutus-extra/blob/master/plutus-size-check/src/Test/Tasty/Plutus/Size.hs), and were used to test functionality for `Rational` and `Integer` as part of the [test suite for `plutus-numeric`](https://github.com/Liqwid-Labs/plutus-extra/blob/master/plutus-numeric/test/size/Main.hs). Many of the `plutus-numeric` operations are just wrappers around existing Plutus functions with a more convenient interface; in particular, for the operations of concern, the impact should be minimal.

The results indicate a considerable size difference between operations on `Integer` and `Rational` performing broadly the same work. While some difference in size is understandable, this seems far in excess of what should be needed. Consider the output fragment below:

```
  Integer
    [omitted]
    abs fits on-chain:                   OK
      Size: 44B
    [omitted]
    signum fits on-chain:                OK
      Size: 65B
  Rational
    [omitted]
    abs fits on-chain:                   OK
      Size: 298B (~0.5KiB)
    [omitted]
    signum fits on-chain:                OK
      Size: 354B (~0.5KiB)
```
Note: these measurements are just for the functions, not for any inputs. We observe that `abs` for `Rational` is nearly 7x the on-chain size as compared to the same operation on `Integer`, and `signum` is nearly 5.5x. This seems excessive. We suspect (based circumstantially on other results) that these blowups extend to other operations too. As our code makes significant use of `Rational`, these costs severely impact our script sizes. It's not clear why these operations have such large inflations.

## Describe the approach you would take to fix this 

Using the tools in `plutus-size-check`, we can benchmark sizes for all the functionality of `Rational`, and then use that as a baseline to implement operations which take up less space on-chain. We have a [range of known optimization techniques](https://github.com/Plutonomicon/plutonomicon/blob/main/scriptsize.md) we can hit this with, but I suspect there's probably low-hanging fruit to be found already. I am happy to contribute such efforts upstream, or initially write a proof-of-concept solution with benchmarking comparisons.

**Comment by michaelpj** [comment]
Firstly, I should point out an assumption you might be making, which is that the size usage of code using `Rational` will be linear in the number of operations you use, with the slope given by your benchmark there.

That's not true in two dimensions, because most of the size is going to be the overhead of the definitions. So in particular:
- Additional uses of an operation `O` will incur essentially 0 size, since they'll just be a reference.
- Additional operations will likely share a lot of definitions, so won't add as much as you might think.

Anyway, it wasn't clear if you were concluding the reverse, but just to be clear.

------------

Additionally, comparing `Rational` and `Integer` is unfair: `Integer` is a builtin type, so doesn't need any additional definitions. `Rational` is just a datatype, and as such we have to include all the code for its definition and the functions that operate on it. So it's inevitably going to be bigger, unless we make `Rational` a builtin (which might be a good idea if it's used enough).

----------

> I am happy to contribute such efforts upstream, or initially write a proof-of-concept solution with benchmarking comparisons.

Please do! We're happy to take contributions of this sort, and we'd be especially happy if they're accompanied by tests that they work well! We could certainly have more fine-grained size tests.
