### ISSUE TITLE
What is a status of Plutus V2?

### ISSUE THREAD

**Issue by anton-k** [input-output-hk/plutus#4285]
### Describe the feature you'd like

I can see that Plutus.V2 was added and it targets some cool features that I'd like to use.
But is it possible to use at the moment do you recommend to use it?

Since plutus-ledger is defined only for plutus V1.
Maybe there is another package for that? 
Does converting to cardano tx work for Plutus V2 and rest of the tools?

**Comment by michaelpj** [comment]
Plutus V2 is really "Plutus VNext". That is, the code is there to enable it, but we won't actually turn it on until it's accumulated enough changes. New language versions are extremely expensive since we have to support them forever, so we'll be batching up changes as much as possible. As such, I wouldn't hold your breath!

**Comment by anton-k** [comment]
Thanks for reply!  So it's better to stick to the V1 for now on the projects.

**Comment by michaelpj** [comment]
It's not like you _can_ use V2 anyway!
