### ISSUE TITLE
Performance of abstract machines

### ISSUE THREAD

**Issue by effectfully** [input-output-hk/plutus#437]
This issue is for discussions about performance of evaluation of Plutus Core programs.

@kwxm has done a great job at figuring out efficiency weak spots of our evaluators. What is not fixed right now is generation of booleans which slows down things a lot. There is a PR (#268) that fixes this, but we probably can do something better (quoting the PR's thread):

> there is another thing to test: whether having booleans as CAFs (i.e. no Quote at all while evaluating things) gives a speedup or no. Quote is rather deeply incorporated into evaluation and we can't just remove it, because many things that use the same constant application machinery, that the machines use, do require unique names, but I think we can do some parameterization here.

**Comment by michaelpj** [comment]
One point against the CPS'd version is that having an explicit "stack" is likely to be better for a debugger, as you can do stack manipulation and so on.

I don't think we'll want to use the same implementation for the "production" machine and the "debugging" machine, but it *is* helpful if they have the same state, since then you can take your debugging state and run the real machine for a bit, etc.

**Comment by kwxm** [comment]
I agree with michaelpj.  As I commented in the PR, the CPS version was quite difficult to get right, since you've just got a big chain of continuations that you can't see inside if there's a bug (although doing the transformation was quite illuminating).  The version with the explicit stack is a lot more transparent, and maybe easier to formalise, and one thing that these experiments tell us is that using that version doesn't seem to be costing us a lot.

**Comment by effectfully** [comment]
> @kwxm has done a great job at figuring out efficiency weak spots of our evaluators. What is not fixed right now is generation of booleans which slows down things a lot. There is a PR (#268) that fixes this, but we probably can do something better (quoting the PR's thread):

The boolean issue has been fixed, but the CEK machine is a rather unoptimal thing, so we should probably think about improving it somehow.
