### ISSUE TITLE
Possible to do `coerce :: CompiledCode a -> CompiledCode b`

### ISSUE THREAD

**Issue by L-as** [input-output-hk/plutus#4436]
### Summary

Right now you can do `coerce :: CompiledCode a -> CompiledCode b`. This is "unsound" in the presence of `applyCode`, because in the context of a function compiled with `compile`, you can pass it an `a` when it was expecting a `b`.

### Steps to reproduce the behavior

```haskell
import PlutusTx.Code (CompiledCode)
import Data.Coerce (coerce)

c :: CompiledCode a -> CompiledCode b
c = coerce
```

### Actual Result

It type checks.

### Expected Result

It shouldn't. The role should be representational rather than phantom AFAICT.

### Describe the approach you would take to fix this

```haskell
type role CompiledCodeIn nominal nominal representational
```
I'm not sure about the roles for the `uni` and `fun` parameters.

### System info

Irrelevant.

**Comment by chessai** [comment]
representational roles can still be coerced. you want a nominal role if you want to prevent coercions.

**Comment by michaelpj** [comment]
In this instance it would be fine for it to be representational, since we treat newtypes the same as their underlying type. But I don't think we care much about that, so nominal would be safer.

I vaguely remembered that I deliberately didn't give this role annotations because it gives something of an illusion of safety: you can always e.g. deserialize with whatever type you like! But it's almost certainly not what you want to coerce it in this way, so we might as well ban it.
