### ISSUE TITLE
Is reference script PlutusV2.txOutReferenceScript representation for Babbage era TxOutCompactRefScript correct?

### ISSUE THREAD

**Issue by anton-k** [input-output-hk/plutus#4776]
### Summary

It seems that PlutusV2 TxOut does not correspond to Babbage era TxOut. I mean we can not convert V2.TxOut to Babbage.TxOut without additional info on how scripts are stored. 

I'm trying to convert Plutus V2 to Babbage Era Tx. The `TxOutCompactRefScript` expects TxOut to contain the full script
as it type goes:

```haskell
  | TxOutCompactRefScript
       {-# UNPACK #-} !(CompactAddr (Crypto era))
       !(CompactForm (Core.Value era))
       !(Datum era)
       !(Core.Script era)  
```

So it contains full script and it seems that we don't win in TxSize except that it's in the UTxO set arounnd TX.
But when I try to convert from Plutus V2 it has ScriptHash in txOutReferenceScript.

Should I calculate the map of ScriptHash to Script for conversion?
It seems that there is no way to store actual scripts in TxOut's on PlutusV2 level. 
I see one way to keep them in datums. Are they supposed to be kept in Datums?

### Steps to reproduce the behavior

Try to convert PlutusV2.TxOut to BabbageTxOut without additional info on ScriptHash to Script map.

### Actual Result

It can not be converted. Or is it on purpose?

### Expected Result

---

### System info

Manjaro Linux

**Comment by michaelpj** [comment]
The Plutus `TxOut` type exists for one purpose: to be the representation of transaction outputs used in `ScriptContext`. It is _not_ intended to be equivalent to the real `TxOut` type for real transactions. It may omit information - in particular in this case we do not include the actual reference script in the `ScriptContext` because that would be pointless bloat, we just put the hash.

**Comment by anton-k** [comment]
Thanks for clarification Michael!
