### ISSUE TITLE
Plutus Core programs with interesting evaluation properties

### ISSUE THREAD

**Issue by effectfully** [input-output-hk/plutus#483]
We need to add Plutus Core programs which evaluation is somehow interesting. For example:

1. a program that takes long to compute, but does not allocate much (already implemented)
2. a program that uses mutual recursion (in process)
3. "Examples with a modest peak allocation but large total allocation would be ones where a GC really helps, and it'll be interesting to look at such examples since IELE currently lacks any GC support in its plutus impl." (citing Duncan)
4. a program with large total allocation to complement the previous case

Anything else?

**Comment by kwxm** [comment]
I wonder if 3 is even possible.  Consider this:

```
let f n m acc = if n==0 then acc else f (n-1) m (m+acc) in f 87654321 12345678 0
```

This performs multiplication by adding 12345678 onto an accumulator 87654321 times.  On the face of it, this looks as if it should do what you want, because it creates lots of intermediate results on the heap which are used only once each, and the eventual result will probably fit into a single 64-bit word.  But what happens to the recursion?  Haskell will presumably perform tail-call elimination because it can see that there's no need to return after the recursive calls to f, but we can't do that in Plutus Core: the CEK machine saves a frame on its stack for every application, and then at the end it'll work back up the stack discarding them: all of these frames will be allocated in the Haskell heap, where they'll use up memory.

I think this will happen with any long-running program.  We have to use recursion if we want to do anything repeatedly, and we don't have any way of doing tail-call optimisation. I'm not sure if that's even possible if you're using combinators for recursion like we do, because it's hard for the machine to look ahead and work out what's going to happen after an application. (Although I was trying to think about exactly what happens with the Z combinator and as usual just got very confused.)

**Comment by michaelpj** [comment]
So we always pay for the depth of our computation tree. That's okay, let's just make a tree that's very wide, i.e. something with multiple recursive calls in the body, so the width (total allocation) is exponentially bigger than the height (peak allocation). 

Fib ought to do it, or something with more than two recursive calls would be even better, but I can't think of anything.

**Comment by kwxm** [comment]
@michaelpj   You're correct about Fibonacci.  I'd managed to convince myself that it had really bad memory consumption, but I was misremembering: that was with the lazy machine.  If you use the CEK machine you can run it for very long periods of time (probably many hours) without any noticeable effect on memory.
