### ISSUE TITLE
Extended UTxO: is DataScript a part of TxOut?

### ISSUE THREAD

**Issue by nau** [input-output-hk/plutus#490]
It's currently unclear from [Extended UTxO](https://github.com/input-output-hk/plutus/blob/master/docs/extended-utxo/README.md) if Data Script is a part of TxOut or not.
If Data Script is a part of TxOut this implies:

1. Data Script content is now a part of a transaction, its hash, hence its TxHash aka TxId.
This means that Data Script can't hold any data that is dependent on its transaction data, for example signatures of its TxHash.
1. Data Script won't be a segregated witness, and thus can't be ever removed.

Either way it should be clarified in the documentation.

**Comment by kwxm** [comment]
I just found this when I was looking at old issues.  Data scripts are no longer scripts, they're objects of the `Data` type, and they are indeed part of the output, and hence part of the transaction.  It hadn't occurred to me that this means that we're limited as to what we can put in the data objects because of circularity.  Is that a problem?

**Comment by michaelpj** [comment]
Both 1 and 2 are correct.

I don't know of a clear explanation of what goes in a segregated witness and what doesn't, perhaps the ledger team have one. But the data value is an integral part of the output, so we really can't drop it.

It's true that the data can't include the transaction id. This can actually be a bit annoying, but I don't know of an easy way to fix it.

**Comment by michaelpj** [comment]
We're changing this a bit, but regardless this should now be unambiguous in the EUTXO doc.
