### ISSUE TITLE
*Q*: Where is `applyArguments`? 

### ISSUE THREAD

**Issue by MangoIV** [input-output-hk/plutus#4959]
It seems that `appplyArguments` is just gone without a note on where it went. 

Can you supply any insight on why it was removed? Thanks in advance.

**Comment by zliu41** [comment]
@MangoIV Sorry for the late reply. We are trying to come up with a better process for monitoring and responding to GH issues.

The `plutus-ledger-api` package is meant to be a library for the ledger, rather than for people writing Plutus scripts, which is why we removed anything not needed by the ledger.

Helper functions useful for writing scripts should certainly exist but elsewhere, e.g., perhaps [here](https://github.com/input-output-hk/plutus-apps/tree/main/plutus-script-utils). I'm unsure whether or not it has `applyArguments` though.

**Comment by effectfully** [comment]
> It seems that `appplyArguments` is just gone without a note on where it went.

We are also working on having a good changelog and keeping it updated.

Question answered, I'm closing this issue. Feel free to reopen if you disagree.
