### ISSUE TITLE
Zigzag encoding formula wrong for negative numbers in plutus-core-specification.pdf

### ISSUE THREAD

**Issue by christianschmitz** [input-output-hk/plutus#5038]
The zigzag encoding formula for negative numbers seems wrong.

In file `./doc/plutus-core-spec/draft-new-specification/plutus-core-specification.pdf` (edition Nov 2022), on page 35, the example says `-1` should become `1` once encoded.

The encoding formula for negative numbers is defined as `2(1 - n) + 1` which encodes `-1` as `5`. I think this should be `-2n - 1`.

Minor: the decoding formula for uneven numbers becoming negative numbers is correct, but could be simplified as `-(n+1)/2`

**Comment by michaelpj** [comment]
cc @kwxm

**Comment by kwxm** [comment]
Yes, I think you're right: thanks for pointing that out!  We'll fix that next week.

**Comment by kwxm** [comment]
@christianschmitz This should be fixed in https://github.com/input-output-hk/plutus/pull/5052.  I tried to add you as a reviewer, but I don't think I'm allowed to do that.

Note that we've recently moved the specification to https://github.com/input-output-hk/plutus/tree/master/doc/plutus-core-spec and added the latex source.

Thanks again for your input.

**Comment by christianschmitz** [comment]
Thank you for correcting this, and thank you for including the latex source!
