### ISSUE TITLE
Strings in Plutus Tx

### ISSUE THREAD

**Issue by mchakravarty** [input-output-hk/plutus#531]
We added string support for the initial Playground release, but we were in a rush and promised to revisit this topic. What is the current situation? What are the alternatives? What do we want to do?

**Comment by michaelpj** [comment]
Current status:
- Strings are implemented as a *static* builtin type. That is, they are hard-coded into the AST like the other builtin types.
- String builtins are provided as *dynamic* builtins. To use these you need to supply an interpretation for them at typecheck-time/run-time.

What we would like to do:
- Dynamic builtin types are supported in a more general way, so that strings do not need to be hardcoded.
    - This is related to @effectfully's ideas about converting PLC values to Haskell values, since one approach to that would require us to have arbitrary Haskell types as dynamic builtin types.
- String builtins as before.

**Comment by jmchapman** [comment]
I believe that they are not sized at the moment. Should they be?

**Comment by kwxm** [comment]
^ This is good. I was worried that if dynamic types were too liberal then it would make it rather pointless having sized types in the type system, but that concern would vanish if we can extend the sizes to work with new types as well.  I suppose you could argue that size isn't important any more if everything's deterministic, but keeping the sizes would force programmers to think more carefully about what they're doing, which is probably a good thing.

**Comment by michaelpj** [comment]
(Sizes are gone now.)

The current state of strings is dissatisfactory in a number of ways:
- We have almost no operations except for concatenation.
- We don't have ways of "show"-ing our primitives.
- The interface with Haskell is awkward: literals are lists of characters, but then we fold over them appending them into a builtin string.
- We don't have a good story for what happens on the chain, where we have vaguely said that strings "won't be present".

I don't have solutions for most of those, just writing down the issues for now.
