### ISSUE TITLE
Multi-currency in the mockchain

### ISSUE THREAD

**Issue by mchakravarty** [input-output-hk/plutus#536]

**Comment by j-mueller** [comment]
After reading Bruno's paper on multi-currency ledgers I think we need these changes:

1. Add a new type of transaction, `TxCurrency`, that introduces a named currency (but has no outputs), and has a `Policy` PLC script that checks whether new value can be forged from it
2. Change the `Value` type from `Value Int` to `Value (Map Currency Int)`
3. Change the `forge` field of regular transaction to `Map Currency (Int, Certificate)` where `Certificate` is like a redeemer script for the `TxCurrency` that is referenced by the currency name
4. Change the emulator to keep track of all `TxCurrency` transactions, and whenever value of a currency is forged we also run the `Policy` script with the `Certificate` that was provided

Questions

* We are going to need a `Map` type for on-chain code, at least with `ByteString` keys. For the beginning I'll just use `[(Key, Value)]`. OK?
* Should ADA be implemented as a special named currency, or a completely separate type (so we would have `Value = (Ada, Map Currency Int)` I'm leaning towards the former
* Having a new type of transaction, `TxCurrency`, that hangs around forever doesn't seem to fit right with the rest of the model but I don't think there is much we can do about that, is there?
* Should the mockchain be parameterised over currency (`Int` or `Map`), transaction and validation?

@mchakravarty @michaelpj @nau

**Comment by j-mueller** [comment]
(Also I would like to point out that the way `TxCurrency` works in the paper is pretty similar to what I had in mind with my "common ancestors" solution to the NFT problem, so I wasn't too far off :) )

**Comment by michaelpj** [comment]
- I've been meaning to implement an elementary `Map` type for this sort of usecase but I haven't got around to it - this might be a good moment!
- I think ADA should just be a named currency.
- AFAIK new currencies never go away, so I guess the transaction just hangs around forever....
- I do like the idea of paramteterizing things, provided we can do it in a way that doesn't make it worse to use.

**Comment by mchakravarty** [comment]
@michaelpj  wrote,

>     * AFAIK new currencies never go away, so I guess the transaction just hangs around forever....

This does seem somewhat worrying, although the equivalent of an ERC20 contract supposedly would also hang around forever.

To "destroy" a currency, we'd need a proof that all its tokens have been collected. Hence, I could imagine the following. Suppose `TxCurrency` includes a another script; let's call it `Destruct`. I can imagine a transaction `TxDestructCurrency` that as input must have *all* the tokens of the to be destroyed currency that are in circulation and a validator for `Destruct` (proving the authority to submit that destructive transaction).

(Especially, if we want to do NFT with the multi-currency extension, this seems very useful.)

**Comment by michaelpj** [comment]
The ability to destroy tokens does seem useful. Maybe pitch it to Bruno?

**Comment by mchakravarty** [comment]
We discussed on Slack that one issue with `destruct` is that we need to provide an incentive to submit (and pay for) that transaction. One option might be that creating a currencies includes a deposit (as part of the fee) that is reimbursed when the currency is being `destruct`ed.

**Comment by j-mueller** [comment]
Here is a new proposal for multi-currency, based on @wadler's idea to make currency names "long" in some cryptographic sense.

* Currencies are identified by script addresses. In terms of the mockchain that means the type  of `Value` changes from `Int` to `Map ByteString Int`. The rules about balanced transactions need to be changed to work with vectors instead of single numbers. (This part of the proposal agrees with Bruno's paper where `Value` is `Map String Int`, a map of currency names to amounts)
* Every transaction that spends a pay-to-script output is allowed to forge value of that output's address. (This is where the proposal differs from Bruno's, where forging can only be done by a special type of transaction)

Apart from that, everything stays the same. In particular, core nodes do not need a registry of known currencies.

**NFTs**

When implementing NFTs this way we need to ensure that the currency can only be forged once, and only one unit of it can be created. We can do this with the following script:

```haskell
data NFT = NFT { nftName :: String, nftBootstrapTxOut :: TxOutput }

-- the validator script (in reality this would be a quoted TH expression)
nftValidator :: NFT -> Data -> Redeemer -> PendingTx -> ()
nftValidator (NFT nm txout) _ _ ptx = 
  let con1 = ptx `spends` txout
      con2 = ptx `forges` 1 (ownAdress ptx)
  if  con1 &&  con2 then () else error 
```

Note that the validator script for a given `NFT` definition is given by `nftValidator nft`, so its address is the hash of `nftValidator nft`.

The key is the `nftBootstrapTxOut` field. Condition `con1` ensures that there is only a single transaction that can forge a value of the NFT (because `txout` can only be spent once, thanks to the no-double-spending rule). Condition `con2` ensures that only a single token of the currency is created, effectively making it non-fungible.

It is of course possible to produce multiple script outputs to the same address of `nftValidator nft` but only one of them can be spent, because the referenced tx output can only be spent once. 

**Currencies**

For a currency where value needs to be created more than once we can write a validator script that ensures the pending transaction produces an output to the currency's address. That way, there is always an unspent transaction output that can be used for forging additional amounts. And here we can use the data & redeemer scripts (which were unused in the `NFT` example) to keep track of how much has been created so far, etc.

**Comment by michaelpj** [comment]
Staring at this a bit, I think this amounts to the following:

- Currencies indexed by addresses.
- Forging controlled by a state machine at that index
    - Can do single token output by not producing new state output.
    - Can do destructible single token by transitioning to a state that accepts the token and does not spend it.
    - Can do more complex monetary policy also.

This actually gets us a lot. We still have the issue that for NFTs each individual token would need to be controlled by a separate transaction state machine, whereas all tokens for a FT can be controlled by a single machine. I think this may be better than Bruno's proposal.

It would be nice to have a single state machine controlling an entire class of NFTs, otherwise we're likely to end up with ad-hoc methods of doing this. Suppose you used NFTs to represent shares in something. Then it's very important to ask "who is allowed to issue shares?". The NFT mechanism described doesn't give us a way to do this, we'd need a separate smart contract that records the tokens which represent valid shares.

**Comment by j-mueller** [comment]
> Can do destructible single token by transitioning to a state that accepts the token and does not spend it

Once the token is created it can only be consumed if it is also produced again to a new output, just like Ada. So we can't do destructible tokens *unless* we allow forged values to be negative.

> We still have the issue that for NFTs each individual token would need to be controlled by a separate transaction state machine

Once the token has been forged, the state machine (script) is not needed anymore, the token can be passed around with pay-to-pubkey outputs and other script outputs just like any other value. I think for a a complex contract it's acceptable to have a couple of initial transactions to set it up, I remember seeing that in a stablecoin implementation on Ethereum.

> Suppose you used NFTs to represent shares in something

I think this example is actually more of a currency than an NFT, because shares of the same thing (company etc) are usually interchangeable, and they are fungible in the sense that 2x the amount of shares gives you 2x the voting rights & dividends

> it's very important to ask "who is allowed to issue shares?"

If shares are represented by some currency `c :: Hash` then any time you want to issue shares you need to spend an output from the `c` address, so the validation script `c` would answer your question. Once the shares have been created they can be passed around like normal Ada without needing to invoke the script each time. (the ledger rule of balanced transaction outputs vs outputs ensures that no new shares are created without involving the script)

**Comment by michaelpj** [comment]
> So we can't do destructible tokens _unless_ we allow forged values to be negative.

We probably want that, then.

> I think for a a complex contract it's acceptable to have a couple of initial transactions to set it up, I remember seeing that in a stablecoin implementation on Ethereum.

I think this is okay for things like "make two roles for a swap contract", but for anything where you might potentially have lots of NFTs (cryptokitties?), I think it's less appealing.

> If shares are represented by some currency `c :: Hash` then any time you want to issue shares you need to spend an output from the `c` address, so the validation script `c` would answer your question. Once the shares have been created they can be passed around like normal Ada without needing to invoke the script each time. (the ledger rule of balanced transaction outputs vs outputs ensures that no new shares are created without involving the script)

This is precisely an argument why having the combined monetary policy is good! The shares example was bad because you're right and they're arguably fungible. However, I don't think it's that outlandish to think that we might have share-like structures where the tokens are non-fungible, e.g. where they correspond to specific roles, or have other purposes too.

**Comment by j-mueller** [comment]
thanks for clarifying, I think I slightly misunderstood your earlier comment. 

> > So we can't do destructible tokens _unless_ we allow forged values to be negative.

> We probably want that, then.

Yeah I agree, it's a nice symmetry. Every time you change the supply you need to involve the script.

> for anything where you might potentially have lots of NFTs (cryptokitties?), I think it's less appealing.

The cryptokitties example is interesting, but at least the new proposal doesn't make it any more difficult than Bruno's does. To make 1000 cryptokitties in the new proposal you need 2 transactions, each with 1000 outputs. To make 1000 cryptokitties in Bruno's proposal you need 1000 transactions. In either case you end up with 1000 unspent outputs at the end.

**Comment by mchakravarty** [comment]
@j-mueller wrote,

> > Can do destructible single token by transitioning to a state that accepts the token and does not spend it
> 
> Once the token is created it can only be consumed if it is also produced again to a new output, just like Ada. So we can't do destructible tokens _unless_ we allow forged values to be negative.

Burning currency by negative forging does seem nice and symmetric (and maybe that's why we want to do it). However, I think, you can always burn value by locking it in an output whose validators always fails.

**Comment by kwxm** [comment]
> @mchakravarty  wrote,
> Burning currency by negative forging does seem nice and symmetric (and maybe that's why we want to do it). However, I think, you can always burn value by locking it in an output whose validator always fails.

But if the validator always fails, doesn't it live on in the UTXO set for the rest of eternity?  Is there some way we can mark an output so that doesn't happen, à la Bitcoin?   https://en.bitcoin.it/wiki/OP_RETURN

**Comment by j-mueller** [comment]
@kwxm wrote,

> But if the validator always fails, doesn't it live on in the UTXO set for the rest of eternity? Is there some way we can mark an output with a special validator so that doesn't happen, à la Bitcoin? https://en.bitcoin.it/wiki/OP_RETURN

Yes it does, unfortunately. Even if we had something like OP_RETURN, you could still write a validator like `\_ _ _ -> error ()` that has the same effect but can't be detected by core nodes. I don't think we have an answer to the possibility of clogging up the UTXO set with unspendable outputs (irrespective of multi- or single-currency)

Maybe a nice solution would be if there was a way to prove to the blockchain/core nodes that an output cannot possibly be spent, we could unlock and keep the value that is locked in it.

**Comment by kwxm** [comment]
Presumably it's undecidable whether an output is unspendable in general.  I suppose that the benefit of OP_RETURN is that it gives you a way of saying that an output is deliberately unspendable, rather than accidentally because of a bad script or something.

**Comment by mchakravarty** [comment]
Having a way to indicate that an output is meant to be unspendable would be good, I think. Or maybe an alternative would be to permit transactions without outputs.

I think, this is something to discuss with the ledger people.

**Comment by michaelpj** [comment]
If we need an explicit way to get rid of currency without leaving a dangling transaction, I think negative forging is nicer than known-unspendable outputs.

**Comment by michaelpj** [comment]
> The cryptokitties example is interesting, but at least the new proposal doesn't make it any more difficult than Bruno's does.

To be clear, I'd like things to be *easier* than in Bruno's proposal ;)

**Comment by j-mueller** [comment]
Closing this - the mockchain has multicurrency now, and #996 deals with updating the paper.
