### ISSUE TITLE
Fuel model

### ISSUE THREAD

**Issue by mchakravarty** [input-output-hk/plutus#540]

**Comment by michaelpj** [comment]
We also need to decide what we call the stuff that we consume. I believe "gas" is disfavoured. "Fuel" would be fine. My semi-serious suggestion is "mana".

**Comment by polinavino** [comment]
The two types of resources that I put as stand-ins right now in the example in the Plutus integration spec are
- number of (beta-)reduction steps
- units of memory needed

In order to validate, a script application computation has to use up to a certain amount of each of the two types of resources. A script has to declare the amount of each that it plans to use, and the computation is stopped as soon as it requires more.

**Comment by kevinhammond** [comment]
@polinavino pointed me at this.  I've done a lot of work on resource analysis.  Happy to discuss any ideas :)

The correct technical term is probably "potential", but "fuel" is a reasonable analogy.  You can also use currency analogies (these are a better analogy than fuel if you have discrete values).  PlutoDollars? :)
