### ISSUE TITLE
`liftCode` using `plcVersion110` in release `1.5.0.0`

### ISSUE THREAD

**Issue by sourabhxyz** [input-output-hk/plutus#5491]
### Describe the feature you'd like

Is this desired? Docs mention using `liftCode` [here](https://github.com/input-output-hk/plutus/blob/1.5.0.0/doc/read-the-docs-site/tutorials/AuctionValidator.hs#L196) but then would such a validator even run? If this is an issue, is there a simple workaround for it for someone who is constrained to use version `1.5.0.0` as a dependency.

Thanks for your time.

**Comment by sourabhxyz** [comment]
Also, seeing [`runCompiler`](https://github.com/input-output-hk/plutus/blob/cfccccc8596859bfaa992100b11199301eb6d2bd/plutus-tx-plugin/src/PlutusTx/Plugin.hs#L376-L438) function, it appears that default compilation is also using version 1.1.0.

Am I missing something or is this an issue? 
Also, I am aware that these issues are resolved for in release 1.6 with support of `target-version` option but cardano node 8.1.2 (if I build it) uses release 1.5 as a dependency.

**Comment by effectfully** [comment]
Apologies for the silence here, we're trying to set up a proper process for reacting to issues, but it clearly didn't work for this one.

>  is there a simple workaround for it for someone who is constrained to use version 1.5.0.0 as a dependency

I've asked around and there doesn't seem to be a workaround if you're hard-constrained to 1.5.0.0 exactly, since we can't mutate a release. However if you can get 1.5.0.1, then you'll have access to `target-version`, since it was backported to that version.

There doesn't appear to be anything else that we can do in the context of this issue, hence I'm closing it. If you disagree, please do feel free to reopen the issue. And once again, apologies for it taking so long for us to respond, we are trying to improve on that front.

**Comment by sourabhxyz** [comment]
Thanks a lot @effectfully for your feedback. We got over it by hacking constraints to use `1.6.0.0` https://github.com/geniusyield/atlas/blob/58a30a5034cc92ac2d3d42594f09b9ac2849c0b4/cabal.project#L37-L53.

**Comment by effectfully** [comment]
Great, I'm glad you'd found a workaround.
