### ISSUE TITLE
Rewrite PIR compilation as a series of PIR-to-PIR transformations

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#610]
Since PLC is a subset of PIR, we can write all the PIR compilation steps as PIR-to-PIR transformations, with a final "lowering" step that just reverses the embedding.

Why do this?
- Other compilers (e.g. GHC) have found this to be a useful strategy.
- Compilation steps become more easily testable and independent.
- Some compilation steps become nicer when they can target PIR (e.g. we can let-bind the fixpoint combinators)
- We can do optimizations in between compilation (esp. dead binding removal)
- If we ever adopt some kind of "Trees that Grow" approach we could even statically assert that passes remove constructs, potentially getting all the way down to PLC.

A sensible pipeline would look like:
- Remove dead lets
- Merge let bindings
- Thunk recursions
- Eliminate recursive let-bindings
- Remove dead lets
- Eliminate datatypes
    - This could be done earlier, but there isn't currently a PIR construct for the "interleaved term and type" binding, so it can't benefit from earlier PIR optimizations.
- Eliminate non-recursive let-bindings
- Lower to PLC

**Comment by michaelpj** [comment]
Note: I actually already did recursion-thunking in this way.

**Comment by wadler** [comment]
LGTM.

**Comment by m-alvarez** [comment]
A problem with this is that the compiler often uses stuff from the PLC standard library (notably eliminating recursive let bindings uses `Language.PlutusCore.StdLib.Data.Function` and `Language.PlutusCore.StdLib.Meta.Data.Tuple` extensively), and these all currently operate on PLC terms. We would need to either:

- Duplicate the PLC stdlib in PIR
- Rewrite the PLC stdlib in PIR and then have the PLC stdlib be equal to the compiled version of the PIR stdlib
- Since the PLC stdlib is just constructing new terms, we could create a class `TermLike` and have both PLC and PIR terms be instances of this, then the PLC stdlib can work with any TermLike and we can leave it mostly unchanged.

Ideas?

**Comment by michaelpj** [comment]
Hm yes, that is annoying. Wouldn't be a problem with Trees that Grow, but oh well.

I was initially repelled by `TermLike`, but I actually can't think of a better way to abstract over this. Note that that wouldn't let you *match* on things, so we'd better not rely on doing that.

**Comment by michaelpj** [comment]
@effectfully would you be okay with that approach?

**Comment by effectfully** [comment]
(Compilation of recursive bindings was originally done on the PIR side, I moved it to PLC, because writing minimal tests for recursive bindings in PLC was very annoying)

> Duplicate the PLC stdlib in PIR

No no no.

> Rewrite the PLC stdlib in PIR and then have the PLC stdlib be equal to the compiled version of the PIR stdlib

Then we need to move some of the PLC tests to PIR. Maybe it's not a big deal, but I like the current separation of concepts.

> Since the PLC stdlib is just constructing new terms, we could create a class TermLike and have both PLC and PIR terms be instances of this, then the PLC stdlib can work with any TermLike and we can leave it mostly unchanged.

A final encoding is good, yes.

There is also another a [suitable initial approach](https://stackoverflow.com/a/27158837).

> @effectfully would you be okay with that approach?

I do feel like we duplicate a lot of things right now. For example both PLC and PIR have `iterApply`, `iterLamAbs` etc and using a type class we can define those combinators for both PLC and PIR. So I do not have anything against the final encoding solution, although it's not certainly perfect.

Maybe it's worth switching to Types that grow, though, I don't know (but let's not do that right now as I'm rewriting a lot of code).

**Comment by m-alvarez** [comment]
For reference, this is what the version with the final encoding will look like
https://github.com/m-alvarez/plutus/tree/TermLike

**Comment by effectfully** [comment]
> For reference, this is what the version with the final encoding will look like
> https://github.com/m-alvarez/plutus/tree/TermLike

This seems to be a pretty minimal things that solves the problem. I like it. Left a comment there.

**Comment by m-alvarez** [comment]
I'm thinking it might be a good idea to submit a separate PR for the final-encoded Term stuff, thoughts?

**Comment by michaelpj** [comment]
Yes, good idea.

**Comment by michaelpj** [comment]
Done.
