### ISSUE TITLE
[Playgrounds Prod] (Meaningless) Error while evaluating Crowdfund contract (decode campaignDeadline)

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/plutus#911]
1. Load Gist: 0fa7aee2bc86f36391409e6e966393ab
2. click on Evaluate under Simulation tab --> you will receive the below error)

"UnexpectedHTTPStatus: OtherError "couldn't decode {\"campaignDeadline\":{\"getSlot\":1},\"campaignTarget\":{\"getAda\":1},\"campaignOwner\":{\"getPubKey\":\"1\"},\"campaignCollectionDeadline\":{\"getSlot\":1}} :: Either [Char] Campaign (\"Error in $.campaignOwner.getPubKey: failed to decode base16\")" (StatusCode 400)
Please try again or contact support for assistance."

Expectation: If the value added inside the campaignDeadline field is not correct we should:
1. make the field red
2. display a meaningful error message, making clear what the issue is and what the end user should do in order to have it working

**Comment by dorin100** [comment]
It seems that the error from this issue is caused by the fact that I used wallet number instead of wallet's pubKey inside the 'campaignOwner' field. 

The above lower the Urgency but it would be nice to have the meaningfulness of the error messages improved too,

**Comment by innocuo** [comment]
I'm just learning about Plutus/Cardano/Haskell, and I just had the same issue with the playground. 

The wallets don't list a pubkey anywhere, and the transaction tab list the wallets with what seem to be their pubkeys, but they're incomplete. So as a newbie, I spent way too much time trying to figure out what I was doing wrong when executing the vesting and crowdfunding sample contracts. I still don't know how to get the wallets pubkeys, but at least I know now it wasn't me.

[The tutorial](https://github.com/input-output-hk/plutus/blob/master/plutus-tutorial/doc/03-wallet-api.adoc) uses the wallet numbers in the pubkey field, so that makes it even more confusing.

**Comment by mchakravarty** [comment]
Can we make sure the pubkeys are prominently displayed somewhere and that the error message is more helpful? Even I have trouble finding the pub keys...
